"""The CLI reference documents every command the CLI registers, and only those (Phase 10, ARC-03).

`docs/reference/cli.md` carried sections for commands that do not exist
(`coordinate init`, `coordinate complete`, `coordinate list`) and none for whole
groups that do (`branch`, `generate`, `seed`, …), while the one guard covered a
single command. This walks the live Typer app: every leaf command has a section
headed by its full name, every long flag the command registers appears in that
section, and every flag the section names is one the command registers. The
skeleton of a section is generated by `scripts/gen_cli_reference.py`; the prose
around it is written by hand.
"""

from __future__ import annotations

import re

import pytest
from doc_snippets import read_doc
from typer.main import get_command
from typer.testing import CliRunner

from confiture.cli.main import app

CLI_DOC = "docs/reference/cli.md"
runner = CliRunner()
_HEADING = re.compile(r"^#{2,4} `confiture ([a-z0-9 -]+)`", re.M)
_FLAG = re.compile(r"--[a-z][a-z0-9-]*")


def _leaf_commands() -> list[str]:
    root = get_command(app)

    def walk(cmd, prefix: str) -> list[str]:  # type: ignore[no-untyped-def]
        subs = getattr(cmd, "commands", None) or {}
        found: list[str] = []
        for name, sub in sorted(subs.items()):
            full = f"{prefix} {name}".strip()
            found.extend(walk(sub, full) if getattr(sub, "commands", None) else [full])
        return found

    return walk(root, "")


LEAF_COMMANDS = _leaf_commands()


def _example_lines(section: str, command: str) -> list[str]:
    """Lines inside fenced code blocks that invoke exactly this command."""
    lines: list[str] = []
    fenced = False
    for line in section.splitlines():
        if line.strip().startswith("```"):
            fenced = not fenced
            continue
        if fenced and re.match(rf"^\s*confiture {re.escape(command)}(\s|$)", line):
            lines.append(line)
    return lines


def _sections(text: str) -> dict[str, str]:
    """Section body per documented command name (heading → text up to the next heading of any level ≤ its own)."""
    matches = list(_HEADING.finditer(text))
    out: dict[str, str] = {}
    for i, m in enumerate(matches):
        level = m.group(0).index(" ")
        end = len(text)
        for later in matches[i + 1 :]:
            if later.group(0).index(" ") <= level:
                end = later.start()
                break
        out[m.group(1).strip()] = text[m.start() : end]
    return out


_ROOT = get_command(app)


def _live_flags(command: str) -> set[str]:
    """The long options the command registers — from its parameters, not from the help prose."""
    cmd = _ROOT
    for part in command.split():
        cmd = cmd.commands[part]
    flags: set[str] = set()
    for param in cmd.params:
        if getattr(param, "hidden", False):
            continue
        flags.update(
            o for o in [*param.opts, *getattr(param, "secondary_opts", [])] if o.startswith("--")
        )
    return flags - {"--help"}


ALL_LIVE_FLAGS: set[str] = set()


def _collect_all_flags() -> None:
    for command in LEAF_COMMANDS:
        ALL_LIVE_FLAGS.update(_live_flags(command))


@pytest.mark.parametrize("command", LEAF_COMMANDS)
def test_every_command_has_a_section_with_its_flags(command: str) -> None:
    sections = _sections(read_doc(CLI_DOC))
    assert command in sections, f"cli.md has no `confiture {command}` section"
    section = sections[command]
    live = _live_flags(command)
    missing = sorted(f for f in live if f not in section)
    assert missing == [], f"`confiture {command}` section is missing flags: {missing}"
    # Prose may name another command's flags; a code example of THIS command may not.
    wrong = sorted(
        f
        for line in _example_lines(section, command)
        for f in _FLAG.findall(line)
        if f not in live and f != "--help"
    )
    assert wrong == [], f"`confiture {command}` examples use flags the command has not got: {wrong}"
    unknown = sorted(f for f in _FLAG.findall(section) if f not in ALL_LIVE_FLAGS and f != "--help")
    assert unknown == [], f"`confiture {command}` section names flags no command has: {unknown}"


def test_every_generated_block_is_current() -> None:
    """`scripts/gen_cli_reference.py --check`: every leaf command has a block and it is byte-current."""
    import importlib.util
    from pathlib import Path

    script = Path(__file__).resolve().parents[3] / "scripts" / "gen_cli_reference.py"
    spec = importlib.util.spec_from_file_location("gen_cli_reference", script)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    problems = module.check(read_doc(CLI_DOC))
    assert problems == [], "cli.md generated blocks:\n  " + "\n  ".join(problems)


def test_no_section_documents_a_command_that_does_not_exist() -> None:
    documented = set(_sections(read_doc(CLI_DOC)))
    groups = {c.rsplit(" ", 1)[0] for c in LEAF_COMMANDS if " " in c}
    fiction = sorted(documented - set(LEAF_COMMANDS) - groups - {"build --dump"})
    assert fiction == [], f"cli.md documents commands that do not exist: {fiction}"


_collect_all_flags()
