"""Seed generation bridge: generate seed SQL files from schema introspection."""

from __future__ import annotations

import dataclasses
from pathlib import Path
from typing import Any

import psycopg

from confiture.core import live_catalog
from confiture.core.model_facts import writable_columns
from confiture.core.schema_model import SchemaModel, Table, ref_for


@dataclasses.dataclass
class SeedGenerationConfig:
    """Configuration for seed generation."""

    table: str
    schema: str = "public"
    row_count: int = 10
    output_dir: Path = dataclasses.field(default_factory=lambda: Path("db/seeds"))
    env: str = "development"
    include_comments: bool = True
    overwrite: bool = False


@dataclasses.dataclass
class SeedGenerationResult:
    """Result of a seed generation operation."""

    table: str
    output_path: Path
    row_count: int
    column_count: int
    success: bool
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        return {
            "table": self.table,
            "output_path": str(self.output_path),
            "row_count": self.row_count,
            "column_count": self.column_count,
            "success": self.success,
            "error": self.error,
        }


class SeedBridge:
    """Generates SQL seed files from schema introspection.

    This is a lightweight bridge that generates INSERT-based seed stubs
    from PostgreSQL table structures. For production-grade seed generation
    with anonymization support, see the fraiseql-data package.
    """

    def __init__(
        self,
        database_url: str,
        *,
        fraiseql_data_available: bool | None = None,
    ) -> None:
        self._database_url = database_url
        self._fraiseql_data = fraiseql_data_available

    def _check_fraiseql_data(self) -> bool:
        """Check if fraiseql-data package is available."""
        if self._fraiseql_data is not None:
            return self._fraiseql_data
        try:
            # Reason: optional dependency — extra 'seed-uuid'; imported where used so the core never requires it
            import fraiseql.data  # noqa: F401  # ty: ignore[unresolved-import]

            return True
        except ImportError:
            return False

    def _get_table_columns(self, table: str, schema: str = "public") -> list[dict[str, Any]]:
        """Introspect columns for a given table; ``writable`` is whether a writer supplies it.

        Which columns those are is the seam's answer (``writable_columns``): every
        column but an identity, a generated column and a ``serial``, which PostgreSQL
        fills and — for ``GENERATED ALWAYS`` — refuses a value for.
        """
        with psycopg.connect(self._database_url) as conn:
            found = live_catalog.columns(conn, schema, table)
        ref = ref_for("table", schema, table)
        model = SchemaModel(tables={ref: Table(name=table, schema=schema, columns=found)})
        writable = {column.folded for column in writable_columns(model, ref)} if found else set()
        return [
            {
                "name": column.folded,
                "type": column.type_text,
                "nullable": not column.not_null,
                "default": column.default,
                "writable": column.folded in writable,
            }
            for column in found
        ]

    def _generate_stub_sql(
        self, table: str, columns: list[dict[str, Any]], config: SeedGenerationConfig
    ) -> str:
        """Generate stub INSERT SQL for a table."""
        lines: list[str] = []

        if config.include_comments:
            lines.append(f"-- Seed data for {config.schema}.{table}")
            lines.append("-- Generated by confiture seed generate")
            lines.append(f"-- Rows: {config.row_count}")
            lines.append("")

        # A column with a default is left to it; one PostgreSQL computes takes no value.
        writable = [c["name"] for c in columns if c["writable"]]
        col_names = [c["name"] for c in columns if c["writable"] and not c.get("default")]
        col_names = col_names or writable
        if not col_names:
            # Every column is PostgreSQL's to fill: a row is inserted with none named.
            lines.extend(
                f"-- INSERT INTO {config.schema}.{table} DEFAULT VALUES;"
                for _ in range(config.row_count)
            )
            return "\n".join(lines)

        cols_str = ", ".join(col_names)

        lines.append(f"-- INSERT INTO {config.schema}.{table} ({cols_str})")
        lines.append("-- VALUES")
        for i in range(config.row_count):
            values = ", ".join(f"<{c['type']}_{i + 1}>" for c in columns if c["name"] in col_names)
            suffix = ";" if i == config.row_count - 1 else ","
            lines.append(f"--     ({values}){suffix}")

        lines.append("")
        lines.append(
            "-- HINT: Replace placeholder values above with actual data or use a generator."
        )

        return "\n".join(lines)

    def generate(self, config: SeedGenerationConfig) -> SeedGenerationResult:
        """Generate a seed file for a table.

        If fraiseql-data is available, delegates to it for richer generation.
        Otherwise, produces a commented-out stub with correct column names.
        ``output_path`` is where the stub goes, whether or not one is written.
        """
        output_path = config.output_dir / config.env / f"{config.table}.sql"
        try:
            columns = self._get_table_columns(config.table, config.schema)
        except psycopg.Error as e:
            return SeedGenerationResult(
                table=config.table,
                output_path=output_path,
                row_count=0,
                column_count=0,
                success=False,
                error=str(e),
            )

        if not columns:
            return SeedGenerationResult(
                table=config.table,
                output_path=output_path,
                row_count=0,
                column_count=0,
                success=False,
                error=f"Table {config.schema}.{config.table} not found or has no columns",
            )

        output_path.parent.mkdir(parents=True, exist_ok=True)

        if output_path.exists() and not config.overwrite:
            return SeedGenerationResult(
                table=config.table,
                output_path=output_path,
                row_count=0,
                column_count=len(columns),
                success=False,
                error=f"File {output_path} already exists. Use --overwrite to replace.",
            )

        sql = self._generate_stub_sql(config.table, columns, config)
        output_path.write_text(sql)

        return SeedGenerationResult(
            table=config.table,
            output_path=output_path,
            row_count=config.row_count,
            column_count=len(columns),
            success=True,
        )
