"""Minimal example of a Confiture scaffold emitter.

Run from this directory::

    confiture generate scaffold --from emitter:emit --schema-dir db/schema

…or programmatically::

    from confiture.core.scaffold.orchestrator import ScaffoldOrchestrator
    from emitter import emit
    ScaffoldOrchestrator(Path("db/schema")).run(emit())

Re-running is safe — the orchestrator allocates new prefixes for each call.
To experiment with the override mechanism, copy one of the generated files
into ``overrides/functions/sandbox/`` and re-run scaffold; that file's slot
will report ``action="skip"`` instead of being overwritten.
"""

from __future__ import annotations

from pathlib import Path

from confiture.core.scaffold.emitter import EmittedFunction

_TARGET = Path("db/schema/functions/sandbox")
_MARKER = "-- GENERATED by example-emitter v0.1.0"


def emit() -> list[EmittedFunction]:
    """Return two trivial SQL functions for the scaffold orchestrator."""
    return [
        EmittedFunction(
            verb="ping",
            subtree=_TARGET,
            content=(
                "CREATE OR REPLACE FUNCTION ping()\n"
                "RETURNS text\n"
                "LANGUAGE sql\n"
                "AS $$\n"
                "    SELECT 'pong'::text;\n"
                "$$;\n"
            ),
            generated_marker=_MARKER,
        ),
        EmittedFunction(
            verb="echo_ping",
            subtree=_TARGET,
            content=(
                "CREATE OR REPLACE FUNCTION echo_ping()\n"
                "RETURNS text\n"
                "LANGUAGE sql\n"
                "AS $$\n"
                "    SELECT ping();\n"
                "$$;\n"
            ),
            generated_marker=_MARKER,
        ),
    ]
