"""Data models for pgTAP test scaffold generation."""

from __future__ import annotations

import dataclasses
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from confiture.models.function_info import FunctionInfo


@dataclasses.dataclass
class PgTAPTest:
    """A single pgTAP test for a PostgreSQL function."""

    function_name: str
    schema: str
    qualified_name: str
    test_name: str
    sql: str

    @classmethod
    def function_exists(cls, info: FunctionInfo) -> PgTAPTest:
        """Generate a test that the function exists."""
        return cls(
            function_name=info.name,
            schema=info.schema,
            qualified_name=info.qualified_name,
            test_name=f"function {info.qualified_name} exists",
            sql=(
                f"SELECT has_function(\n"
                f"    '{info.schema}',\n"
                f"    '{info.name}',\n"
                f"    'Function {info.qualified_name} should exist'\n"
                f");"
            ),
        )

    @classmethod
    def function_returns(cls, info: FunctionInfo) -> PgTAPTest:
        """Generate a test for the function's return type."""
        return_type = info.return_type or "void"
        return cls(
            function_name=info.name,
            schema=info.schema,
            qualified_name=info.qualified_name,
            test_name=f"function {info.qualified_name} returns {return_type}",
            sql=(
                f"SELECT function_returns(\n"
                f"    '{info.schema}',\n"
                f"    '{info.name}',\n"
                f"    '{return_type}',\n"
                f"    'Function {info.qualified_name} should return {return_type}'\n"
                f");"
            ),
        )

    @classmethod
    def function_volatility(cls, info: FunctionInfo) -> PgTAPTest:
        """Generate a test for the function's volatility."""
        volatility = info.volatility.value.lower()
        return cls(
            function_name=info.name,
            schema=info.schema,
            qualified_name=info.qualified_name,
            test_name=f"function {info.qualified_name} is {volatility}",
            sql=(
                f"SELECT is_volatile('{info.schema}', '{info.name}') IS NOT NULL\n"
                f"    OR is_stable('{info.schema}', '{info.name}') IS NOT NULL\n"
                f"    OR is_immutable('{info.schema}', '{info.name}') IS NOT NULL,\n"
                f"    'Function {info.qualified_name} should have {volatility} volatility';"
            ),
        )


@dataclasses.dataclass
class PgTAPFile:
    """A generated pgTAP test file."""

    schema: str
    database: str
    generated_at: str
    tests: list[PgTAPTest]
    function_count: int

    def render(self) -> str:
        """Render to pgTAP SQL test file."""
        lines = [
            "-- Generated by confiture generate pgtap",
            f"-- Schema: {self.schema}  Database: {self.database}  Generated: {self.generated_at}",
            "-- DO NOT EDIT — regenerate with: confiture generate pgtap ...",
            "",
            "\\set ON_ERROR_STOP 1",
            "\\set ON_ERROR_ROLLBACK 1",
            "",
            "BEGIN;",
            "",
            f"SELECT plan({len(self.tests)});",
            "",
        ]

        for test in self.tests:
            lines.append(f"-- {test.test_name}")
            lines.append(test.sql)
            lines.append("")

        lines.extend(["SELECT * FROM finish();", "", "ROLLBACK;"])

        return "\n".join(lines)
