-- Table DDL for the blog schema, in the shape FraiseQL's CQRS convention
-- produces: a normalized tb_* command side and a denormalized tv_* query side.
--
-- This file is CHECKED IN, not generated at build time. Confiture builds from
-- DDL — db/schema/ is the single source of truth — so the DDL has to be present
-- in a fresh clone for `confiture build --env local` to have anything to build.
-- (It was gitignored once. The build then found only extensions and indexes,
-- emitted a schema of indexes on tables that did not exist, and reported
-- success.)
--
-- Manual edits belong in separate files (e.g. db/schema/20_indexes/) so that
-- re-deriving this one from the type definitions stays a mechanical operation.
--
-- Schema version: 1.0.0

-- =============================================================================
-- User Tables (CQRS Pattern)
-- =============================================================================

-- Command side: Normalized table for writes
CREATE TABLE IF NOT EXISTS tb_user (
    -- Sacred Trinity (FraiseQL pattern)
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pk_user UUID DEFAULT gen_random_uuid() NOT NULL,
    identifier TEXT,

    -- User fields (from @fraise_type)
    email TEXT NOT NULL,
    username TEXT NOT NULL,
    full_name TEXT NOT NULL,
    bio TEXT,
    avatar_url TEXT,
    is_active BOOLEAN DEFAULT true NOT NULL,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Constraints
    CONSTRAINT pk_tb_user PRIMARY KEY (id),
    CONSTRAINT uq_tb_user_pk UNIQUE (pk_user),
    CONSTRAINT uq_tb_user_email UNIQUE (email),
    CONSTRAINT uq_tb_user_username UNIQUE (username),

    -- Business logic constraints
    CONSTRAINT ck_tb_user_email_format CHECK (email LIKE '%@%'),
    CONSTRAINT ck_tb_user_username_length CHECK (
        LENGTH(username) >= 3 AND LENGTH(username) <= 30
    )
);

-- Query side: Denormalized JSONB table for fast reads
CREATE TABLE IF NOT EXISTS tv_user (
    id UUID PRIMARY KEY,
    data JSONB NOT NULL,

    -- Generated columns for indexing
    email TEXT GENERATED ALWAYS AS (data->>'email') STORED,
    username TEXT GENERATED ALWAYS AS (data->>'username') STORED,
    is_active BOOLEAN GENERATED ALWAYS AS ((data->>'isActive')::boolean) STORED,
    -- Written by the projector, not generated: a STORED generated column's
    -- expression must be IMMUTABLE, and every text -> timestamptz cast is
    -- STABLE (it reads DateStyle and TimeZone).
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table comments
COMMENT ON TABLE tb_user IS 'Users - command side (normalized)';
COMMENT ON TABLE tv_user IS 'Users - query side (denormalized JSONB)';

COMMENT ON COLUMN tb_user.pk_user IS 'Public UUID exposed in API';
COMMENT ON COLUMN tb_user.identifier IS 'Optional business identifier (e.g., email)';
COMMENT ON COLUMN tv_user.data IS 'Complete user data with computed fields (post count, comment count)';

-- =============================================================================
-- Post Tables (CQRS Pattern)
-- =============================================================================

-- Command side: Normalized table for writes
CREATE TABLE IF NOT EXISTS tb_post (
    -- Sacred Trinity
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pk_post UUID DEFAULT gen_random_uuid() NOT NULL,
    identifier TEXT,

    -- Foreign key to user
    fk_user UUID NOT NULL,

    -- Post fields
    title VARCHAR(500) NOT NULL,
    slug VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT,
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    is_published BOOLEAN DEFAULT false NOT NULL,
    published_at TIMESTAMPTZ,
    view_count INTEGER DEFAULT 0 NOT NULL,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Constraints
    CONSTRAINT pk_tb_post PRIMARY KEY (id),
    CONSTRAINT uq_tb_post_pk UNIQUE (pk_post),
    CONSTRAINT uq_tb_post_slug UNIQUE (slug),
    CONSTRAINT fk_tb_post_user FOREIGN KEY (fk_user)
        REFERENCES tb_user(pk_user) ON DELETE CASCADE,

    -- Business logic constraints
    CONSTRAINT ck_tb_post_title_length CHECK (LENGTH(title) >= 1),
    CONSTRAINT ck_tb_post_slug_format CHECK (slug ~ '^[a-z0-9-]+$'),
    CONSTRAINT ck_tb_post_view_count CHECK (view_count >= 0),
    CONSTRAINT ck_tb_post_published_at CHECK (
        (is_published = false AND published_at IS NULL) OR
        (is_published = true AND published_at IS NOT NULL)
    )
);

-- Query side: Denormalized JSONB table
CREATE TABLE IF NOT EXISTS tv_post (
    id UUID PRIMARY KEY,
    data JSONB NOT NULL,

    -- Generated columns for indexing
    slug TEXT GENERATED ALWAYS AS (data->>'slug') STORED,
    is_published BOOLEAN GENERATED ALWAYS AS ((data->>'isPublished')::boolean) STORED,
    view_count INTEGER GENERATED ALWAYS AS ((data->>'viewCount')::integer) STORED,
    -- Written by the projector, not generated: a STORED generated column's
    -- expression must be IMMUTABLE, and every text -> timestamptz cast is
    -- STABLE (it reads DateStyle and TimeZone).
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table comments
COMMENT ON TABLE tb_post IS 'Posts - command side (normalized)';
COMMENT ON TABLE tv_post IS 'Posts - query side (denormalized with author and comments)';

COMMENT ON COLUMN tb_post.slug IS 'URL-friendly post identifier (auto-generated from title)';
COMMENT ON COLUMN tb_post.tags IS 'PostgreSQL array for topic tags';
COMMENT ON COLUMN tv_post.data IS 'Complete post with embedded author and comments';

-- =============================================================================
-- Comment Tables (CQRS Pattern)
-- =============================================================================

-- Command side: Normalized table for writes
CREATE TABLE IF NOT EXISTS tb_comment (
    -- Sacred Trinity
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    pk_comment UUID DEFAULT gen_random_uuid() NOT NULL,
    identifier TEXT,

    -- Foreign keys
    fk_post UUID NOT NULL,
    fk_user UUID NOT NULL,
    fk_parent_comment UUID,

    -- Comment fields
    content TEXT NOT NULL,
    is_edited BOOLEAN DEFAULT false NOT NULL,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Constraints
    CONSTRAINT pk_tb_comment PRIMARY KEY (id),
    CONSTRAINT uq_tb_comment_pk UNIQUE (pk_comment),
    CONSTRAINT fk_tb_comment_post FOREIGN KEY (fk_post)
        REFERENCES tb_post(pk_post) ON DELETE CASCADE,
    CONSTRAINT fk_tb_comment_user FOREIGN KEY (fk_user)
        REFERENCES tb_user(pk_user) ON DELETE CASCADE,
    CONSTRAINT fk_tb_comment_parent FOREIGN KEY (fk_parent_comment)
        REFERENCES tb_comment(pk_comment) ON DELETE CASCADE,

    -- Business logic constraints
    CONSTRAINT ck_tb_comment_content_length CHECK (LENGTH(content) >= 1),
    CONSTRAINT ck_tb_comment_not_self_parent CHECK (pk_comment != fk_parent_comment)
);

-- Query side: Denormalized JSONB table
CREATE TABLE IF NOT EXISTS tv_comment (
    id UUID PRIMARY KEY,
    data JSONB NOT NULL,

    -- Generated columns for indexing
    post_id UUID GENERATED ALWAYS AS ((data->>'postId')::uuid) STORED,
    author_id UUID GENERATED ALWAYS AS ((data->'author'->>'id')::uuid) STORED,
    -- Written by the projector, not generated: a STORED generated column's
    -- expression must be IMMUTABLE, and every text -> timestamptz cast is
    -- STABLE (it reads DateStyle and TimeZone).
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table comments
COMMENT ON TABLE tb_comment IS 'Comments - command side (normalized)';
COMMENT ON TABLE tv_comment IS 'Comments - query side (denormalized with author and post)';

COMMENT ON COLUMN tb_comment.fk_parent_comment IS 'Parent comment for nested replies (null for top-level)';
COMMENT ON COLUMN tv_comment.data IS 'Complete comment with embedded author and post info';

-- =============================================================================
-- Indexes (Basic)
-- =============================================================================

-- Uniqueness on the optional business identifier.
--
-- This is a partial *index*, not a table constraint: PostgreSQL has no
-- `CONSTRAINT ... UNIQUE (col) WHERE ...`. The predicate keeps the index off
-- the rows that have no identifier, which is most of them.
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_user_identifier
    ON tb_user(identifier) WHERE identifier IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_post_identifier
    ON tb_post(identifier) WHERE identifier IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_comment_identifier
    ON tb_comment(identifier) WHERE identifier IS NOT NULL;

-- User indexes
CREATE INDEX IF NOT EXISTS idx_tb_user_email ON tb_user(email);
CREATE INDEX IF NOT EXISTS idx_tb_user_username ON tb_user(username);
CREATE INDEX IF NOT EXISTS idx_tb_user_active ON tb_user(is_active);
CREATE INDEX IF NOT EXISTS idx_tb_user_created ON tb_user(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tv_user_email ON tv_user(email);
CREATE INDEX IF NOT EXISTS idx_tv_user_username ON tv_user(username);
CREATE INDEX IF NOT EXISTS idx_tv_user_active ON tv_user(is_active);

-- Post indexes
CREATE INDEX IF NOT EXISTS idx_tb_post_user ON tb_post(fk_user);
CREATE INDEX IF NOT EXISTS idx_tb_post_slug ON tb_post(slug);
CREATE INDEX IF NOT EXISTS idx_tb_post_published ON tb_post(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_tb_post_created ON tb_post(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tb_post_tags ON tb_post USING gin(tags);

CREATE INDEX IF NOT EXISTS idx_tv_post_slug ON tv_post(slug);
CREATE INDEX IF NOT EXISTS idx_tv_post_published ON tv_post(is_published) WHERE is_published = true;
CREATE INDEX IF NOT EXISTS idx_tv_post_created ON tv_post(created_at DESC);

-- Comment indexes
CREATE INDEX IF NOT EXISTS idx_tb_comment_post ON tb_comment(fk_post);
CREATE INDEX IF NOT EXISTS idx_tb_comment_user ON tb_comment(fk_user);
CREATE INDEX IF NOT EXISTS idx_tb_comment_parent ON tb_comment(fk_parent_comment);
CREATE INDEX IF NOT EXISTS idx_tb_comment_created ON tb_comment(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tv_comment_post ON tv_comment(post_id);
CREATE INDEX IF NOT EXISTS idx_tv_comment_author ON tv_comment(author_id);

-- =============================================================================
-- Triggers (Updated_at automation)
-- =============================================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to all tb_* tables
CREATE TRIGGER trigger_tb_user_updated_at
    BEFORE UPDATE ON tb_user
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_tb_post_updated_at
    BEFORE UPDATE ON tb_post
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_tb_comment_updated_at
    BEFORE UPDATE ON tb_comment
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
