"""The lint inventory holds every fact the differ reads about a table.

Before the model, a column in the inventory was a name, a line, a type as written,
``not_null`` and a default — so the differ kept 830 lines of parse of its own, and
the two disagreed: a primary key declared at table level made a column ``NOT NULL``
to the differ and nullable to the inventory, which is why ``confiture drift``
reported a database applied verbatim from its own DDL as drifted.
"""

from __future__ import annotations

from confiture.core.linting.inventory import build_inventory
from confiture.core.schema_model import Column, Constraint
from confiture.core.type_lattice import canonical_type

DDL = """\
CREATE TABLE a.t (
    id INT PRIMARY KEY,
    n VARCHAR(50) NOT NULL DEFAULT 'x',
    pid INT REFERENCES b.p(id) ON DELETE CASCADE,
    g INT GENERATED ALWAYS AS (id * 2) STORED,
    k BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CHECK (id > 0)
);
"""


def _table():
    (table,) = build_inventory(DDL).tables
    return table


def _column(name: str) -> Column:
    return next(c for c in _table().columns if c.folded == name)


def test_a_table_carries_its_constraints() -> None:
    assert _table().constraints == [
        Constraint(kind="primary_key", columns=("id",)),
        Constraint(
            kind="foreign_key",
            columns=("pid",),
            ref_table="b.p",
            ref_columns=("id",),
            on_delete="CASCADE",
        ),
        Constraint(kind="check", expression="id > 0"),
    ]


def test_a_column_carries_its_type_twice_identity_and_spelling() -> None:
    n = _column("n")
    assert n.raw_sql_type == "VARCHAR(50)"
    # The typmod is part of a column type's identity: varchar(50) and
    # varchar(100) are two types (#320).
    assert n.type_key == canonical_type("varchar(50)")
    assert n.type_text == "varchar(50)"


def test_a_column_carries_what_its_clauses_declare() -> None:
    n = _column("n")
    assert n.not_null
    assert n.default == "'x'"
    assert _column("g").generated == "id * 2"
    assert _column("g").generated_kind == "stored"
    assert _column("k").identity == "by default"


def test_an_identity_column_is_not_null() -> None:
    assert _column("k").not_null


def test_a_primary_key_marks_its_columns_wherever_it_is_declared() -> None:
    (table,) = build_inventory("CREATE TABLE t (id INT, CONSTRAINT pk PRIMARY KEY (id));").tables
    (column,) = table.columns
    assert column.primary_key
    assert column.not_null
    assert table.has_primary_key


def test_a_column_keeps_the_line_a_finding_prints() -> None:
    assert _column("n").line == 3
    assert _column("k").line == 6


def test_alter_table_add_constraint_reaches_the_table() -> None:
    (table,) = build_inventory(
        "CREATE TABLE t (id INT, pid INT);\n"
        "ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (pid) REFERENCES p (id);\n"
        "ALTER TABLE t ADD PRIMARY KEY (id);\n"
    ).tables
    assert [c.kind for c in table.constraints] == ["foreign_key", "primary_key"]
    assert next(c for c in table.columns if c.folded == "id").not_null


def test_an_added_column_brings_its_own_clauses() -> None:
    (table,) = build_inventory(
        "CREATE TABLE t (id INT);\nALTER TABLE t ADD COLUMN pid INT NOT NULL REFERENCES p;\n"
    ).tables
    assert table.constraints == [Constraint(kind="foreign_key", columns=("pid",), ref_table="p")]
    assert table.columns[-1].not_null


def test_a_quoted_default_keeps_its_escaping() -> None:
    (table,) = build_inventory("CREATE TABLE t (c TEXT DEFAULT 'it''s');").tables
    assert table.columns[0].default == "'it''s'"
