"""The one model of what a schema declares: tables, columns, constraints, indexes, types.

Every reader of a DDL tree answers in these types, and each is defined here once.
There were six models of a table in this package, and a column's nullability was
derived six ways from four sources; a fact one reader modelled and another did not
reached an artefact every time — a primary key declared at table level read as a
nullable column, a generated DDL file that lost a column's identity.

The module is data and nothing else. It imports no parser and no database driver,
so a tool that only has to *hold* a schema — a seed generator, a parity fixture —
pays for neither. Everything is frozen: a model is a statement of what a tree
declares, and a reader that wants a different one builds a different one.

Two fields about a type, deliberately (#275). ``type_key`` is the **identity**,
``type_lattice.canonical_type`` of the parser's spelling, and decides whether two
columns hold one type. ``raw_sql_type`` is the **spelling** generated DDL writes:
the readable keyword with the typmod the author wrote (``VARCHAR(50)``), because
the length lives in the spelling. ``type_text`` is a third reading — the type as
the author wrote it — which is what a finding prints.

Identity is ``(schema, name)`` with a missing qualifier folded to
:data:`~confiture.core.schema_identity.DEFAULT_SCHEMA` (#313). The spelling never
invents a qualifier: :attr:`Table.qualified` prints what the author wrote.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import asdict, dataclass, field
from typing import Any, Literal

from confiture.core.schema_identity import DEFAULT_SCHEMA

#: What a constraint that is not a column property enforces.
ConstraintKind = Literal["primary_key", "unique", "check", "foreign_key"]

#: ``GENERATED ALWAYS AS IDENTITY`` or ``GENERATED BY DEFAULT AS IDENTITY``.
IdentityKind = Literal["always", "by default"]

#: ``DEFERRABLE INITIALLY IMMEDIATE`` / ``… DEFERRED``; ``None`` is ``NOT DEFERRABLE``.
Deferral = Literal["immediate", "deferred"]

#: How a generated column holds its value. ``virtual`` arrived with PostgreSQL 18,
#: where it is also what ``GENERATED ALWAYS AS (…)`` with neither keyword means.
GeneratedKind = Literal["stored", "virtual"]


@dataclass(frozen=True)
class ObjectRef:
    """A **bucket**: what makes two ``CREATE`` statements *candidates* for one object.

    ``schema`` is folded and defaulted, so an unqualified ``CREATE VIEW v`` and
    ``CREATE VIEW public.v`` are one object — what
    :data:`~confiture.core.schema_identity.DEFAULT_SCHEMA` is for. ``name`` is
    folded for the same reason; :attr:`display` keeps the spelling a change
    prints.

    ``signature`` is the inventory's :func:`~confiture.core.linting.inventory.signature_bucket`
    — the canonical *names* of a routine's input parameter types, without their
    own schemas. It is deliberately not the full signature: a dict key cannot
    express "a type schema written on one side and left off the other still
    matches", so ``fn(bigint)`` and ``fn(int8)`` must land in one bucket and
    :func:`~confiture.core.linting.inventory.signatures_match` decides inside it.
    Keying on the full signature reported an added and a dropped function where
    one routine had been respelled (CLAUDE.md, #275).
    """

    kind: str
    schema: str
    name: str
    signature: tuple[str, ...] | None
    #: The spelling a change prints. Out of the key deliberately: it carries the
    #: *signature as written*, and ``fn(bigint)`` and ``fn(int8)`` are one
    #: routine written two ways (#275). Keying on it reported a dropped and an
    #: added function where a type had merely been respelled.
    display: str = field(compare=False)

    @property
    def qualified(self) -> str:
        """How a change names the object: the spelling the author wrote."""
        return self.display


def ref_for(kind: str, schema: str | None, name: str) -> ObjectRef:
    """The bucket of a relation-like object: ``(kind, folded schema, name)``, no signature."""
    return ObjectRef(
        kind=kind,
        schema=(schema or DEFAULT_SCHEMA).lower(),
        name=name,
        signature=None,
        display=qualified_name(schema, name),
    )


def qualified_name(schema: str | None, name: str) -> str:
    """``schema.name`` when the author wrote a schema, the bare name when they did not."""
    return f"{schema}.{name}" if schema else name


@dataclass(frozen=True)
class Column:
    """A column, whole.

    ``name`` keeps the author's case with quoting stripped, and ``folded`` is the
    parser's spelling; ``line`` is where the name is written, which is what a
    finding points at. ``not_null`` is what PostgreSQL will record: ``NOT NULL``,
    a primary key — on the column or at table level — and an identity column all
    set it. ``default`` is the default expression's text, ``identity`` the kind
    of ``GENERATED … AS IDENTITY``, ``generated`` the expression of a
    ``GENERATED ALWAYS AS (…)`` column and ``generated_kind`` how it is held.
    """

    name: str
    folded: str
    line: int
    type_text: str | None = None
    type_key: str | None = None
    raw_sql_type: str | None = None
    not_null: bool = False
    default: str | None = None
    identity: IdentityKind | None = None
    generated: str | None = None
    generated_kind: GeneratedKind | None = None
    primary_key: bool = False


@dataclass(frozen=True)
class Constraint:
    """A table constraint: a primary key, a UNIQUE, a CHECK or a foreign key.

    ``name`` is empty when the schema wrote none — PostgreSQL generates one at
    apply time, and nothing here invents it. ``columns`` are the columns it
    covers, whichever of the three places the grammar allows it was written in;
    ``ref_table`` / ``ref_columns`` / ``on_delete`` / ``on_update`` describe a
    foreign key, and an empty ``ref_columns`` means the referenced primary key.
    ``expression`` is a CHECK's condition, rendered.
    """

    kind: ConstraintKind
    name: str = ""
    columns: tuple[str, ...] = ()
    ref_table: str | None = None
    ref_columns: tuple[str, ...] = ()
    on_delete: str | None = None
    on_update: str | None = None
    expression: str | None = None
    deferrable: Deferral | None = None


@dataclass(frozen=True)
class Index:
    """An index on one table.

    ``columns`` holds each key as written — a column name or a rendered
    expression. ``method`` is the access method; PostgreSQL's grammar fills in
    ``btree`` when the statement writes no ``USING``, and so does the catalog.
    """

    name: str | None
    table: str
    columns: tuple[str, ...]
    unique: bool = False
    where: str | None = None
    method: str | None = None


@dataclass(frozen=True)
class Table:
    """A table: its columns, its constraints and its indexes."""

    name: str
    schema: str | None = None
    columns: tuple[Column, ...] = ()
    constraints: tuple[Constraint, ...] = ()
    indexes: tuple[Index, ...] = ()

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)


@dataclass(frozen=True)
class EnumType:
    """``CREATE TYPE … AS ENUM``: its labels, in declaration order."""

    name: str
    schema: str | None = None
    values: tuple[str, ...] = ()

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)


@dataclass(frozen=True)
class Sequence:
    """``CREATE SEQUENCE``, with the options a comparison reads."""

    name: str
    schema: str | None = None
    start: int | None = None
    increment: int | None = None
    min_value: int | None = None
    max_value: int | None = None

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)


@dataclass(frozen=True)
class SchemaModel:
    """Everything one schema declares, each object under its :class:`ObjectRef`."""

    tables: Mapping[ObjectRef, Table] = field(default_factory=dict)
    enum_types: Mapping[ObjectRef, EnumType] = field(default_factory=dict)
    sequences: Mapping[ObjectRef, Sequence] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """A JSON-ready rendering, objects in identity order, for goldens and dumps."""

        def section(objects: Mapping[ObjectRef, Any]) -> list[dict[str, Any]]:
            ordered = sorted(objects.items(), key=lambda item: (item[0].schema, item[0].name))
            return [asdict(obj) for _, obj in ordered]

        return {
            "tables": section(self.tables),
            "enum_types": section(self.enum_types),
            "sequences": section(self.sequences),
        }
