"""The one model of what a schema declares: tables, types, sequences, routines and views.

Every reader of a DDL tree answers in these types, and each is defined here once.
A second model of a table is how a fact one reader models and another does not
reaches an artefact — a primary key declared at table level read as a nullable
column, a generated DDL file that loses a column's identity.

The module is data and nothing else. It imports no parser and no database driver,
so a tool that only has to *hold* a schema — a seed generator, a parity fixture —
pays for neither. Everything is frozen: a model is a statement of what a tree
declares, and a reader that wants a different one builds a different one.

Two fields about a type, deliberately (#275). ``type_key`` is the **identity**,
``type_lattice.canonical_type`` of the parser's spelling, and decides whether two
columns hold one type. ``raw_sql_type`` is the **spelling** generated DDL writes:
the readable keyword with the typmod the author wrote (``VARCHAR(50)``), because
the length lives in the spelling. ``type_text`` is a third reading — the type as
the author wrote it — which is what a finding prints.

Identity is ``(schema, name)`` with a missing qualifier folded to
:data:`~confiture.core.schema_identity.DEFAULT_SCHEMA` (#313). The spelling never
invents a qualifier: :attr:`Table.qualified` prints what the author wrote.

A routine's identity adds its input argument types, and they are two fields for
the same reason a column's type is: :attr:`Routine.signature` is the spelling a
finding prints, :attr:`Routine.signature_key` the ``(schema, canonical type)`` per
argument that decides whether two routines are one. Compare keys through
``inventory.signatures_match``: a type schema written on one side and left off the
other still matches (#302), which no dict key can express — so a routine's
:class:`ObjectRef` is a bucket, and :attr:`SchemaModel.routines` holds every
overload that falls in it.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable, Iterable, Iterator, Mapping
from dataclasses import asdict, dataclass, field, replace
from enum import StrEnum
from typing import Any, Literal, TypeVar

from confiture.core.schema_identity import DEFAULT_SCHEMA

#: What a constraint that is not a column property enforces.
ConstraintKind = Literal["primary_key", "unique", "check", "foreign_key", "exclusion"]

#: ``GENERATED ALWAYS AS IDENTITY`` or ``GENERATED BY DEFAULT AS IDENTITY``.
IdentityKind = Literal["always", "by default"]

#: ``DEFERRABLE INITIALLY IMMEDIATE`` / ``… DEFERRED``; ``None`` is ``NOT DEFERRABLE``.
Deferral = Literal["immediate", "deferred"]

#: How a generated column holds its value. ``virtual`` arrived with PostgreSQL 18,
#: where it is also what ``GENERATED ALWAYS AS (…)`` with neither keyword means.
GeneratedKind = Literal["stored", "virtual"]

#: What a column's default is, as the reader that held its parse tree classified it:
#: a ``nextval(…)``, a call to a value generator (``gen_random_uuid()``, ``uuidv7()``,
#: …), a constant, or any other expression.
DefaultKind = Literal["sequence", "generator", "constant", "expression"]


class ValueSource(StrEnum):
    """Where a column's value comes from when a row is written.

    One answer for every reader that asks — a seed writer (which columns it
    supplies), parity (what a ``serial`` is in the catalog), drift (whose default
    is its own) and the tenant rules (which keys cannot collide) — derived from
    the column's own fields, never from its default's text.
    """

    IDENTITY = "identity"
    GENERATED = "generated"
    SEQUENCE = "sequence"
    GENERATOR = "generator"
    EXPRESSION = "expression"
    CONSTANT = "constant"
    NONE = "none"

    @property
    def filled_by_postgresql(self) -> bool:
        """PostgreSQL writes the value; a writer does not supply it (``writable_columns``)."""
        return self in (ValueSource.IDENTITY, ValueSource.GENERATED, ValueSource.SEQUENCE)

    @property
    def unique_without_author_input(self) -> bool:
        """Every row gets a value no other row has, whatever the writer does."""
        return self in (ValueSource.IDENTITY, ValueSource.SEQUENCE, ValueSource.GENERATOR)


#: What ``CREATE FUNCTION``, ``CREATE PROCEDURE`` and ``CREATE AGGREGATE`` define.
RoutineKind = Literal["function", "procedure", "aggregate"]

#: What PostgreSQL records a routine may do; ``volatile`` when nothing is written.
Volatility = Literal["immutable", "stable", "volatile"]

#: A routine's input argument types, each as ``(schema, canonical name)``: the
#: schema is ``None`` where the argument named none, which matches any (#302).
Signature = tuple[tuple[str | None, str], ...]


@dataclass(frozen=True)
class ObjectRef:
    """A **bucket**: what makes two ``CREATE`` statements *candidates* for one object.

    ``schema`` is folded and defaulted, so an unqualified ``CREATE VIEW v`` and
    ``CREATE VIEW public.v`` are one object — what
    :data:`~confiture.core.schema_identity.DEFAULT_SCHEMA` is for. ``name`` is
    folded for the same reason; :attr:`display` keeps the spelling a change
    prints.

    ``signature`` is the inventory's :func:`~confiture.core.linting.inventory.signature_bucket`
    — the canonical *names* of a routine's input parameter types, without their
    own schemas. It is deliberately not the full signature: a dict key cannot
    express "a type schema written on one side and left off the other still
    matches", so ``fn(bigint)`` and ``fn(int8)`` must land in one bucket and
    :func:`~confiture.core.linting.inventory.signatures_match` decides inside it.
    Keyed on the full signature, one respelled routine would report as an added
    and a dropped function (#275).
    """

    kind: str
    schema: str
    name: str
    signature: tuple[str, ...] | None
    #: The spelling a change prints. Out of the key deliberately: it carries the
    #: *signature as written*, and ``fn(bigint)`` and ``fn(int8)`` are one
    #: routine written two ways (#275). Keyed on it, a respelled type would report
    #: as a dropped and an added function.
    display: str = field(compare=False)

    @property
    def qualified(self) -> str:
        """How a change names the object: the spelling the author wrote."""
        return self.display


def ref_for(kind: str, schema: str | None, name: str) -> ObjectRef:
    """The bucket of a relation-like object: ``(kind, folded schema, name)``, no signature."""
    return ObjectRef(
        kind=kind,
        schema=(schema or DEFAULT_SCHEMA).lower(),
        name=name,
        signature=None,
        display=qualified_name(schema, name),
    )


def qualified_name(schema: str | None, name: str) -> str:
    """``schema.name`` when the author wrote a schema, the bare name when they did not."""
    return f"{schema}.{name}" if schema else name


@dataclass(frozen=True)
class RelationName:
    """A relation one object names — a foreign key's target, an index's table, a parent.

    Two parts, never one string (#478). PostgreSQL accepts a dot inside a quoted
    name (``app."a.b"``), so ``schema.name`` text cannot be taken apart again: the
    parser hands the two over separately, the catalog reads them separately, and
    they stay that way. Both parts are as the parser holds them — an unquoted
    part already folded, a quoted one kept — and ``schema`` is ``None`` when the
    author wrote none; :attr:`identity` defaults it, which is how two references
    are compared.
    """

    schema: str | None
    name: str

    @property
    def identity(self) -> tuple[str, str]:
        """``(schema, name)`` the relation is found under: a missing schema defaulted."""
        return self.schema or DEFAULT_SCHEMA, self.name

    @property
    def qualified(self) -> str:
        """``schema.name`` as written, for a message — never to be split again."""
        return qualified_name(self.schema, self.name)

    def ref(self, kind: str = "table") -> ObjectRef:
        """The model's key of the relation, as :func:`ref_for` builds it."""
        return ref_for(kind, self.schema, self.name)


@dataclass(frozen=True)
class Column:
    """A column, whole.

    ``name`` keeps the author's case with quoting stripped, and ``folded`` is the
    parser's spelling; ``file`` and ``line`` are where the name is written — the
    file that wrote the column, which an ``ALTER … ADD COLUMN`` makes another
    than its table's, and the line in it — which is what a finding points at.
    Where a column is written is not what it is: two trees declaring one column
    from different files declare one column, so neither takes part in equality. ``not_null`` is what PostgreSQL will record: ``NOT NULL``,
    a primary key — on the column or at table level — and an identity column all
    set it. ``default`` is the default expression's text, ``identity`` the kind
    of ``GENERATED … AS IDENTITY``, ``generated`` the expression of a
    ``GENERATED ALWAYS AS (…)`` column and ``generated_kind`` how it is held.
    """

    name: str
    folded: str
    line: int = field(compare=False)
    type_text: str | None = None
    type_key: str | None = None
    raw_sql_type: str | None = None
    not_null: bool = False
    default: str | None = None
    identity: IdentityKind | None = None
    generated: str | None = None
    generated_kind: GeneratedKind | None = None
    primary_key: bool = False
    file: str | None = field(default=None, compare=False)
    #: What :attr:`default` is, read from its parse tree by the reader that held it.
    #: Derived from the default, so it takes no part in equality.
    default_kind: DefaultKind | None = field(default=None, compare=False)

    @property
    def value_source(self) -> ValueSource:
        """Where this column's value comes from (:class:`ValueSource`)."""
        if self.identity:
            return ValueSource.IDENTITY
        if self.generated is not None:
            return ValueSource.GENERATED
        if (self.raw_sql_type or "").upper() in SERIAL_TYPES:
            return ValueSource.SEQUENCE
        return ValueSource(self.default_kind) if self.default_kind else ValueSource.NONE


#: ``serial`` and its siblings are not types: PostgreSQL stores an integer, NOT NULL,
#: a ``nextval`` default and a sequence the column owns, none of which DDL wrote.
SERIAL_TYPES = frozenset({"SMALLSERIAL", "SERIAL", "BIGSERIAL"})


@dataclass(frozen=True)
class Constraint:
    """A table constraint: a primary key, a UNIQUE, a CHECK, a foreign key or an EXCLUDE.

    ``name`` is empty when the schema wrote none — PostgreSQL generates one at
    apply time, and nothing here invents it. ``columns`` are the columns it
    covers, whichever of the three places the grammar allows it was written in;
    ``ref_table`` / ``ref_columns`` / ``on_delete`` / ``on_update`` describe a
    foreign key, and an empty ``ref_columns`` means the referenced primary key.
    ``expression`` is a CHECK's condition, rendered.

    An exclusion constraint's ``columns`` are its elements, each a column name or a
    rendered expression as an index's keys are, with ``key_options`` alongside as
    on :class:`Index`; ``operators`` runs alongside too, the operator each element
    is compared with (``&&``, ``OPERATOR(pg_catalog.=)``). ``method`` is its index
    access method and ``where`` its partial predicate, rendered.
    """

    kind: ConstraintKind
    name: str = ""
    columns: tuple[str, ...] = ()
    ref_table: RelationName | None = None
    ref_columns: tuple[str, ...] = ()
    on_delete: str | None = None
    on_update: str | None = None
    expression: str | None = None
    deferrable: Deferral | None = None
    operators: tuple[str, ...] = ()
    method: str | None = None
    where: str | None = None
    key_options: tuple[str, ...] = ()


@dataclass(frozen=True)
class Index:
    """An index on one table.

    ``columns`` holds each key as written — a column name or a rendered
    expression. ``method`` is the access method; PostgreSQL's grammar fills in
    ``btree`` when the statement writes no ``USING``, and so does the catalog.
    ``backs_constraint`` is set on an index that exists only to back a PRIMARY KEY,
    UNIQUE or EXCLUDE constraint — PostgreSQL's, never declared by DDL, so it is
    never *extra* to it; only the catalog knows it. ``key_options`` runs alongside
    ``columns``: what each key's element writes after the key — its collation,
    operator class and ordering (``gin_trgm_ops``, ``DESC NULLS LAST``), ``""``
    for a key that writes none, and ``()`` when no key writes any.
    """

    name: str | None
    table: RelationName
    columns: tuple[str, ...]
    unique: bool = False
    where: str | None = None
    method: str | None = None
    backs_constraint: bool = False
    key_options: tuple[str, ...] = ()
    #: Alongside ``columns``: whether each key is an expression rather than a
    #: column. ``None`` where the reader recorded nothing (a model written
    #: before it did), and a key shaped like an identifier is then a column.
    expressions: tuple[bool, ...] | None = None


@dataclass(frozen=True)
class Table:
    """A table: its columns, its constraints and its indexes."""

    name: str
    schema: str | None = None
    columns: tuple[Column, ...] = ()
    constraints: tuple[Constraint, ...] = ()
    indexes: tuple[Index, ...] = ()

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)

    @property
    def relation(self) -> RelationName:
        """The table as another object names it: its schema and its name, apart."""
        return RelationName(self.schema, self.name)

    def column(self, folded: str) -> Column | None:
        """The column the parser spells *folded*, or ``None``."""
        return next((column for column in self.columns if column.folded == folded), None)

    def constraints_of(self, kind: ConstraintKind) -> tuple[Constraint, ...]:
        """The table's constraints of one kind, in the order the tree declared them."""
        return tuple(constraint for constraint in self.constraints if constraint.kind == kind)


@dataclass(frozen=True)
class EnumType:
    """``CREATE TYPE … AS ENUM``: its labels, in declaration order."""

    name: str
    schema: str | None = None
    values: tuple[str, ...] = ()

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)


@dataclass(frozen=True)
class Sequence:
    """``CREATE SEQUENCE``, with the options a comparison reads."""

    name: str
    schema: str | None = None
    start: int | None = None
    increment: int | None = None
    min_value: int | None = None
    max_value: int | None = None

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)


@dataclass(frozen=True)
class Routine:
    """One routine — a function, a procedure or an aggregate — and one overload of it.

    ``signature`` is the input argument types as the reader found them written —
    the DDL's own words, or ``format_type``'s — and ``signature_key`` the same
    types canonicalised, which is what makes two routines one. ``OUT`` and
    ``TABLE`` parameters are in neither: PostgreSQL does not resolve a call by them.

    ``body`` is the text between the ``AS`` quotes, as written, and ``None`` where
    that text is not SQL (``LANGUAGE c`` / ``internal``: a symbol). ``returns`` is
    the result type as the reader spells it, ``None`` for a procedure.
    ``security_definer``, ``search_path_pinned`` and ``volatility`` are what
    PostgreSQL records — invoker, unpinned and ``volatile`` when nothing is written.
    """

    name: str
    schema: str | None = None
    kind: RoutineKind = "function"
    signature: str = ""
    signature_key: Signature = ()
    returns: str | None = None
    language: str | None = None
    body: str | None = None
    security_definer: bool = False
    search_path_pinned: bool = False
    volatility: Volatility = "volatile"

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)

    @property
    def identity(self) -> str:
        """``schema.name(arguments)``, spelled as the reader found it."""
        return f"{self.qualified}({self.signature})"


@dataclass(frozen=True)
class View:
    """A view or a materialized view.

    ``definition`` is the query as the reader holds it: the DDL's ``SELECT``
    rendered, or ``pg_get_viewdef``'s deparse — two spellings of one query, which
    is why a definition is compared through one deparser or not at all.
    ``indexes`` are a materialized view's; a view has none.
    """

    name: str
    schema: str | None = None
    materialized: bool = False
    definition: str | None = None
    indexes: tuple[Index, ...] = ()

    @property
    def kind(self) -> str:
        return "matview" if self.materialized else "view"

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)


@dataclass(frozen=True)
class Trigger:
    """A trigger a user created, named with the table it fires on.

    A trigger's name is unique per *table*, not per schema, so its identity is
    ``(schema, table, name)``: two tables may each carry a ``trg_touch``.
    """

    name: str
    table: str
    schema: str | None = None

    @property
    def qualified(self) -> str:
        """``schema.table.trigger``, the schema only where it was written."""
        return f"{qualified_name(self.schema, self.table)}.{self.name}"


@dataclass(frozen=True)
class ColumnReference:
    """What a foreign key column points at: the table, found, and the column in it.

    ``table`` is the table the model holds when it holds it — a bare name found
    wherever ``search_path`` put it — and otherwise the reference as identity
    reads it. ``column`` is the referenced column; ``None`` where the key names
    none and the model does not hold the target's primary key to say which.
    """

    table: ObjectRef
    column: str | None


@dataclass(frozen=True)
class ColumnFacts:
    """What a writer supplying one column must respect.

    ``type_key`` / ``raw_sql_type`` / ``not_null`` / ``default`` are the column's.
    ``unique`` is true where one PRIMARY KEY, UNIQUE constraint or unique index
    covers this column alone — declared on the column, at table level or as an
    index. ``checks`` are the CHECK expressions that name it, ``enum_values`` the
    labels of the enum its type is, ``foreign_key`` what it references.
    """

    name: str
    type_key: str | None
    raw_sql_type: str | None
    not_null: bool
    default: str | None
    unique: bool
    checks: tuple[str, ...] = ()
    enum_values: tuple[str, ...] | None = None
    foreign_key: ColumnReference | None = None


def routine_ref(routine: Routine) -> ObjectRef:
    """The bucket of a routine: its kind, folded schema, name and argument type names."""
    return ObjectRef(
        kind=routine.kind,
        schema=(routine.schema or DEFAULT_SCHEMA).lower(),
        name=routine.name,
        signature=tuple(name for _schema, name in routine.signature_key),
        display=routine.identity,
    )


#: The prefix pg_tviews reads a ``CREATE TABLE … AS`` target by: ``tv_<entity>``.
TVIEW_PREFIX = "tv_"

#: The schema pg_tviews keeps every object of its own in, whatever ``search_path``
#: says (its control file's ``schema``, from 0.1.0-beta.20).
TVIEWS_SCHEMA = "tviews"


@dataclass(frozen=True)
class TView:
    """A pg_tviews TVIEW: ``CREATE TABLE tv_<entity> AS SELECT …``.

    pg_tviews turns that statement into a table, a backing view ``v_<entity>``
    and triggers on each base table, and lists it in ``tviews.registry``. The
    model holds the TVIEW as one object — its relation and its query — and its
    parts belong to it. ``definition`` is the query as the reader holds it: the
    DDL's ``SELECT`` rendered, or the registry's ``query``.

    ``logged`` and ``fillfactor`` are pg_tviews' ``options`` keys of those names:
    what the tree pins (``UNLOGGED``, ``WITH (fillfactor = n)``, ``SET LOGGED``),
    ``None`` where it pins nothing, or what the registry holds, every key set.
    """

    name: str
    schema: str | None = None
    definition: str | None = None
    logged: bool | None = None
    fillfactor: int | None = None

    @property
    def entity(self) -> str:
        return self.name.removeprefix(TVIEW_PREFIX)

    @property
    def backing_view(self) -> str:
        return f"v_{self.entity}"

    @property
    def qualified(self) -> str:
        return qualified_name(self.schema, self.name)


#: The pg_tviews ``options`` keys a tree can pin, as :class:`TView` holds them.
TVIEW_OPTIONS = ("logged", "fillfactor")


def tview_ref(tview: TView) -> ObjectRef:
    """The bucket of a TVIEW: its schema and its ``tv_*`` relation."""
    return ref_for("tview", tview.schema, tview.name)


def view_ref(view: View) -> ObjectRef:
    """The bucket of a view or a materialized view."""
    return ref_for(view.kind, view.schema, view.name)


def trigger_ref(trigger: Trigger) -> ObjectRef:
    """The bucket of a trigger: its schema, and its table and name together."""
    return ref_for("trigger", trigger.schema, f"{trigger.table}.{trigger.name}")


_K = TypeVar("_K")
_V = TypeVar("_V")


class _ReadOnly(Mapping[_K, _V]):
    """A mapping nothing writes to: a copy of what the model was built from.

    Not ``MappingProxyType``, which cannot be copied or pickled: a caller that
    deep-copies a model, or hands one to another process, gets it whole.
    """

    __slots__ = ("_data",)

    def __init__(self, data: Mapping[_K, _V]) -> None:
        self._data = dict(data)

    def __getitem__(self, key: _K) -> _V:
        return self._data[key]

    def __iter__(self) -> Iterator[_K]:
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    def __repr__(self) -> str:
        return repr(self._data)


@dataclass(frozen=True)
class OtherObject:
    """An object the model holds by identity and definition only.

    A schema, an extension, a domain, a composite or range type, a policy, a
    rule, an event trigger, extended statistics, a foreign table, a foreign-data
    wrapper, a server, a publication, a conversion, an operator class or family,
    an access method: the kinds no typed section holds. ``kind``, ``schema`` and
    ``name`` are its identity as ``ObjectRef`` keys it (schema folded and
    defaulted, a policy or rule named ``table.name``); ``definition`` is what
    decides whether it changed, ``None`` from a reader that read only that it
    exists (``Coverage`` says which).
    """

    kind: str
    schema: str
    name: str
    definition: str | None = None


#: Every kind an :class:`OtherObject` is — what drift names in ``subject.kind``,
#: published as an enum in ``_common.schema.json``.
OTHER_OBJECT_KINDS = (
    "schema",
    "extension",
    "domain",
    "type",
    "policy",
    "rule",
    "event_trigger",
    "statistics",
    "foreign_table",
    "foreign_data_wrapper",
    "server",
    "publication",
    "conversion",
    "operator_class",
    "operator_family",
    "access_method",
)

#: The kinds of :data:`OTHER_OBJECT_KINDS` that live in no schema; their
#: ``OtherObject.schema`` is the default schema their identity folds to, not a place.
SCHEMALESS_KINDS = frozenset(
    {
        "schema",
        "extension",
        "event_trigger",
        "foreign_data_wrapper",
        "server",
        "publication",
        "access_method",
    }
)

#: The object kinds a typed section holds; every other tracked kind is an
#: :class:`OtherObject`.
TYPED_KINDS = frozenset(
    {
        "table",
        "sequence",
        "function",
        "procedure",
        "aggregate",
        "view",
        "matview",
        "trigger",
        "tview",
    }
)


def other_ref(obj: OtherObject) -> ObjectRef:
    """The bucket of an object the model holds by identity and definition."""
    return ObjectRef(
        kind=obj.kind, schema=obj.schema, name=obj.name, signature=None, display=obj.name
    )


#: How deeply a reader read a section: that each object exists, or what it is.
CoverageDepth = Literal["existence", "definition"]

#: Who wrote what a model says: an author's DDL, or PostgreSQL's catalog. A tree's
#: model is the author's whichever of its two readings it is (``SchemaRead.model``
#: or ``.catalogued``): the spelling is still the author's. A database's is the
#: catalog's. A comparison's rules follow from the two sides' (``differ.policy_between``).
Provenance = Literal["author", "catalog"]

#: The model's sections, in the order its wire writes them.
SECTIONS = (
    "tables",
    "enum_types",
    "sequences",
    "routines",
    "views",
    "triggers",
    "tviews",
    "other_objects",
)

#: What every reader reads: the sections a table-level comparison needs.
_STRUCTURAL = ("tables", "enum_types", "sequences")


@dataclass(frozen=True)
class Coverage:
    """What a reader read: each section of the model, and how deeply.

    A model says what a schema holds only for the sections it covers. Silence in
    a section nobody read is not absence: a database read without its views has
    no views in its model, and a comparison must not call every declared view
    missing. A tree covers every section it can declare; a live read, the
    sections it was asked for.
    """

    sections: tuple[tuple[str, CoverageDepth], ...] = tuple(
        (section, "definition") for section in _STRUCTURAL
    )

    @classmethod
    def of(cls, sections: Mapping[str, CoverageDepth]) -> Coverage:
        """The coverage of *sections*, in the model's own order."""
        return cls(tuple((s, sections[s]) for s in SECTIONS if s in sections))

    @classmethod
    def every(cls) -> Coverage:
        """Every section, whole: what reading DDL gives."""
        return cls.of(dict.fromkeys(SECTIONS, "definition"))

    def depth(self, section: str) -> CoverageDepth | None:
        """How deeply *section* was read, or ``None`` when it was not."""
        return dict(self.sections).get(section)

    def shared(self, other: Coverage, section: str) -> CoverageDepth | None:
        """How deeply both read *section*: the shallower of the two, or ``None``."""
        mine, theirs = self.depth(section), other.depth(section)
        if mine is None or theirs is None:
            return None
        return "definition" if mine == theirs == "definition" else "existence"


@dataclass(frozen=True)
class SchemaModel:
    """Everything one schema declares, each object under its :class:`ObjectRef`.

    A routine's reference is a bucket (see :func:`routine_ref`), so
    :attr:`routines` maps it to every overload in it, in declaration order.
    Frozen through and through: each mapping is a read-only copy of the one it
    was built from, so neither a reader nor the builder can change a model after
    it is made.
    """

    tables: Mapping[ObjectRef, Table] = field(default_factory=dict)
    enum_types: Mapping[ObjectRef, EnumType] = field(default_factory=dict)
    sequences: Mapping[ObjectRef, Sequence] = field(default_factory=dict)
    routines: Mapping[ObjectRef, tuple[Routine, ...]] = field(default_factory=dict)
    views: Mapping[ObjectRef, View] = field(default_factory=dict)
    triggers: Mapping[ObjectRef, Trigger] = field(default_factory=dict)
    tviews: Mapping[ObjectRef, TView] = field(default_factory=dict)
    other_objects: Mapping[ObjectRef, OtherObject] = field(default_factory=dict)
    #: What the reader read (:class:`Coverage`). Not what the schema is, so not
    #: part of equality: a tree and the database built from it are one schema.
    coverage: Coverage = field(default_factory=Coverage, compare=False)
    #: Who wrote it (:data:`Provenance`). Like coverage, not what the schema is.
    source: Provenance = field(default="author", compare=False)

    def __post_init__(self) -> None:
        for name in SECTIONS:
            value = getattr(self, name)
            if not isinstance(value, _ReadOnly):
                object.__setattr__(self, name, _ReadOnly(value))

    def all_routines(self) -> list[Routine]:
        """Every routine, overloads included, in identity order."""
        return [routine for _, found in _ordered(self.routines) for routine in found]

    def to_dict(self) -> dict[str, Any]:
        """A JSON-ready rendering, objects in identity order, for goldens and dumps."""

        def section(objects: Mapping[ObjectRef, Any]) -> list[dict[str, Any]]:
            return [asdict(obj) for _, obj in _ordered(objects)]

        return {
            "tables": section(self.tables),
            "enum_types": section(self.enum_types),
            "sequences": section(self.sequences),
            "routines": [asdict(routine) for routine in self.all_routines()],
            "views": section(self.views),
            "triggers": section(self.triggers),
            "tviews": section(self.tviews),
            "other_objects": section(self.other_objects),
            "coverage": dict(self.coverage.sections),
            "source": self.source,
        }

    def to_json(self) -> str:
        """The model's wire: :meth:`to_dict`, keys sorted, so one model is one text.

        ``schema-model.schema.json`` publishes its shape. Sorted keys make the bytes
        a function of the model alone, not of the order fields are declared in.
        """
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)

    @staticmethod
    def from_json(text: str) -> SchemaModel:
        """The model :meth:`to_json` wrote *text* from.

        Each object's reference is derived from the object, as every reader derives
        it — a table's from its schema and name, a routine's from its signature — so
        the wire carries no key a reader could disagree with.
        """
        return _model_from_dict(json.loads(text))


def _ordered(objects: Mapping[ObjectRef, Any]) -> list[tuple[ObjectRef, Any]]:
    return sorted(
        objects.items(),
        key=lambda item: (item[0].schema, item[0].name, item[0].kind, item[0].signature or ()),
    )


def _column_from(data: dict[str, Any]) -> Column:
    return Column(**data)


def _relation_from(data: dict[str, Any] | str | None) -> RelationName | None:
    """A relation from its wire: ``{"schema", "name"}``.

    A model written before the relation was two parts carried ``schema.name``
    text; it reads as split on its last dot, which is what it meant when it was
    written — a dot inside a name was already lost then.
    """
    if data is None:
        return None
    if isinstance(data, str):
        schema, _, name = data.rpartition(".")
        return RelationName(schema or None, name)
    return RelationName(data["schema"], data["name"])


def _constraint_from(data: dict[str, Any]) -> Constraint:
    """A constraint from its wire; one written before EXCLUDE was modelled reads without it."""
    return Constraint(
        **{
            **data,
            "ref_table": _relation_from(data.get("ref_table")),
            "columns": tuple(data["columns"]),
            "ref_columns": tuple(data["ref_columns"]),
            "operators": tuple(data.get("operators", ())),
            "key_options": tuple(data.get("key_options", ())),
        }
    )


def _index_from(data: dict[str, Any]) -> Index:
    """An index from its wire; one written before ``key_options`` existed reads as none."""
    table = _relation_from(data["table"])
    if table is None:
        raise ValueError(f"an index on no relation: {data!r}")
    return Index(
        **{
            **data,
            "table": table,
            "columns": tuple(data["columns"]),
            "expressions": (
                None if data.get("expressions") is None else tuple(data["expressions"])
            ),
            "key_options": tuple(data.get("key_options", ())),
        }
    )


def _table_from(data: dict[str, Any]) -> Table:
    return Table(
        **{
            **data,
            "columns": tuple(_column_from(c) for c in data["columns"]),
            "constraints": tuple(_constraint_from(c) for c in data["constraints"]),
            "indexes": tuple(_index_from(i) for i in data["indexes"]),
        }
    )


def _routine_from(data: dict[str, Any]) -> Routine:
    key = tuple((schema, name) for schema, name in data["signature_key"])
    return Routine(**{**data, "signature_key": key})


def _view_from(data: dict[str, Any]) -> View:
    return View(**{**data, "indexes": tuple(_index_from(i) for i in data["indexes"])})


def _keyed[T](
    items: list[dict[str, Any]],
    read: Callable[[dict[str, Any]], T],
    ref: Callable[[T], ObjectRef],
) -> dict[ObjectRef, T]:
    return {ref(obj): obj for obj in map(read, items)}


def _model_from_dict(data: dict[str, Any]) -> SchemaModel:
    routines: dict[ObjectRef, list[Routine]] = {}
    for routine in map(_routine_from, data["routines"]):
        routines.setdefault(routine_ref(routine), []).append(routine)
    return SchemaModel(
        tables=_keyed(data["tables"], _table_from, lambda t: ref_for("table", t.schema, t.name)),
        enum_types=_keyed(
            data["enum_types"],
            lambda d: EnumType(**{**d, "values": tuple(d["values"])}),
            lambda e: ref_for("type", e.schema, e.name),
        ),
        sequences=_keyed(
            data["sequences"],
            lambda d: Sequence(**d),
            lambda s: ref_for("sequence", s.schema, s.name),
        ),
        routines={ref: tuple(found) for ref, found in routines.items()},
        views=_keyed(data["views"], _view_from, view_ref),
        triggers=_keyed(data["triggers"], lambda d: Trigger(**d), trigger_ref),
        # A wire written before TVIEWs were modelled has none (#504).
        tviews=_keyed(data.get("tviews", []), lambda d: TView(**d), tview_ref),
        other_objects=_keyed(data.get("other_objects", []), lambda d: OtherObject(**d), other_ref),
        # A wire written before coverage was recorded claims only the structural
        # sections, which every reader has always read.
        coverage=Coverage.of(data["coverage"]) if "coverage" in data else Coverage(),
        # A wire written before provenance was recorded does not say: read as an author's.
        source=data.get("source", "author"),
    )


def _primary_key(table: Table) -> tuple[str, ...]:
    declared = table.constraints_of("primary_key")
    if declared:
        return declared[0].columns
    return tuple(column.folded for column in table.columns if column.primary_key)


def with_referenced_keys(model: SchemaModel) -> SchemaModel:
    """*model* with each foreign key naming the columns it references, as PostgreSQL holds it.

    ``REFERENCES parent`` with no column list references ``parent``'s primary
    key, and the catalog names those columns: the key is the same key written
    either way. A target the model does not hold, or one with no primary key,
    leaves the key as written.
    """
    keys = {table.relation.identity: _primary_key(table) for table in model.tables.values()}

    def resolved(constraint: Constraint) -> Constraint:
        if constraint.kind != "foreign_key" or constraint.ref_columns:
            return constraint
        if constraint.ref_table is None:
            return constraint
        key = keys.get(constraint.ref_table.identity, ())
        return replace(constraint, ref_columns=key) if key else constraint

    return replace(
        model,
        tables={
            ref: replace(table, constraints=tuple(map(resolved, table.constraints)))
            for ref, table in model.tables.items()
        },
    )


# ---------------------------------------------------------------------------
# Parity: a database built from a tree reads back as the tree
# ---------------------------------------------------------------------------

#: What PostgreSQL rewrites on the way into its catalog, and why each is not a
#: difference between a tree and the database built from it. Every entry is a
#: disagreement measured in ``tests/integration/test_parity_normalisations_are_measured.py``,
#: which fails the day PostgreSQL stops making it — so none can outlive its cause.
PARITY_NORMALISATIONS: dict[str, str] = {
    "generated_names": (
        "an unnamed constraint or index is given a name at apply time (child_pid_fkey, "
        "child_pid_idx); a name of PostgreSQL's own shape is no name, on either side"
    ),
    "analysed_expressions": (
        "a CHECK, a generation expression, an index's expression key and a partial "
        "index's predicate are stored analysed — implicit casts added, IN written back "
        "as = ANY (ARRAY[…]) — so what is compared is that one exists, never its text, "
        "unless the tree is materialised (read back from a scratch database); a key "
        "that is a plain column name is compared as written. A default is stored "
        "analysed too; set aside here, the engine compares it as the value it is, a "
        "parse tree whose constants the database's server spells (ddl_walk.same_value)"
    ),
    "spellings": (
        "a column's name, type and position as a file wrote them (`UserId`, "
        "`VARCHAR(50)`, line 12) are spelling; the catalog knows the folded name, "
        "format_type's spelling and no file. type_key is the identity compared"
    ),
    "serial": (
        "serial is not a type: the catalog holds an integer, NOT NULL, a nextval "
        "default and a sequence the column owns, none of which the tree wrote"
    ),
    "sequence_bounds": ("a sequence's unset bounds read back as its type's own bounds"),
    "schema_spelling": (
        "the catalog always knows a relation's schema and spells it in "
        "pg_get_indexdef / pg_get_constraintdef only when search_path would miss it; "
        "the tree spells what the author wrote. Identity is (schema, name) with "
        "DEFAULT_SCHEMA folded in, on both sides"
    ),
    "backing_indexes": (
        "PostgreSQL creates an index to back each PRIMARY KEY and UNIQUE constraint; "
        "the DDL declares the constraint and never the index"
    ),
    "declaration_order": (
        "the catalog lists a table's constraints and indexes by name, a tree by where "
        "it declared them; which exist is the fact, not their order"
    ),
    "routine_spellings": (
        "a routine's argument and result types as a file wrote them (`int8`, "
        "`RETURNS int4`) are spelling; the catalog knows format_type's (`bigint`, "
        "`integer`). signature_key is the identity compared"
    ),
    "tview_defaults": (
        "a TVIEW option the tree does not pin is pg_tviews' to choose, and the registry "
        "holds every key: a stock pg_tviews creates a TVIEW unlogged with fillfactor 85, "
        "so those values are no pin, on either side"
    ),
    "view_definitions": (
        "a view's query is stored as a parse tree and read back through "
        "pg_get_viewdef's deparse — qualified, reparenthesised, `*` expanded — so what "
        "is compared is that one exists, unless the tree is materialised and both "
        "queries come through one deparser"
    ),
}

#: What an expression is compared as: present.
_EXPRESSION = "<expression>"

#: An index key that is a column, not an expression.
_COLUMN_KEY = re.compile(r"[A-Za-z_][A-Za-z0-9_$]*")


#: An ascending sequence's bounds when none is written, per sequence type.
_DEFAULT_MAX = frozenset({2**15 - 1, 2**31 - 1, 2**63 - 1})


#: Every normalisation: what a comparison between a tree and a database applies.
ALL_PARITY_RULES = frozenset(PARITY_NORMALISATIONS)


def _fold_schema(schema: str | None, rules: frozenset[str]) -> str | None:
    return (schema or DEFAULT_SCHEMA).lower() if "schema_spelling" in rules else schema


def _parity_relation(relation: RelationName, rules: frozenset[str]) -> RelationName:
    """*relation* by its identity: the catalog always names the schema a tree may omit."""
    return RelationName(*relation.identity) if "schema_spelling" in rules else relation


def _generated_name(table: str, name: str | None) -> bool:
    return name is not None and bool(
        re.fullmatch(rf"{re.escape(table)}(_.+)?_(pkey|key|fkey|check|excl)\d*", name)
    )


def _generated_index_name(table: str, name: str | None) -> bool:
    return name is not None and bool(re.fullmatch(rf"{re.escape(table)}_.+_idx\d*", name))


def _expression(text: str | None, rules: frozenset[str]) -> str | None:
    if text is None or "analysed_expressions" not in rules:
        return text
    return _EXPRESSION


def parity_column(column: Column, rules: frozenset[str] = ALL_PARITY_RULES) -> Column:
    """*column* as *rules* compare it: spelling, ``serial`` and analysed expressions folded."""
    if "serial" in rules and column.value_source is ValueSource.SEQUENCE:
        # `type_key` already says `serial` is `integer`; only the spelling differs.
        column = replace(column, raw_sql_type=None, not_null=True, default=None, default_kind=None)
    if "spellings" in rules:
        column = replace(column, name=column.folded, line=0, type_text=None)
    return replace(
        column,
        default=_expression(column.default, rules),
        generated=_expression(column.generated, rules),
    )


def parity_constraint(
    table: str, constraint: Constraint, rules: frozenset[str] = ALL_PARITY_RULES
) -> Constraint:
    """*constraint* of *table* as *rules* compare it: a generated name is no name."""
    generated = "generated_names" in rules and _generated_name(table, constraint.name)
    return replace(
        constraint,
        name="" if generated else constraint.name,
        expression=_expression(constraint.expression, rules),
        ref_table=(
            None if constraint.ref_table is None else _parity_relation(constraint.ref_table, rules)
        ),
    )


def parity_indexes(
    indexes: Iterable[Index],
    rules: frozenset[str] = ALL_PARITY_RULES,
    declared: frozenset[str] = frozenset(),
) -> list[tuple[Index, Index]]:
    """Each of *indexes* that *rules* compare, paired with how they compare it.

    An index backing a constraint is the constraint's, which the DDL declares
    instead (``backing_indexes``): it is not compared — unless the other side
    *declared* an index of its name, as ``UNIQUE USING INDEX`` does.
    """
    return [
        (index, _parity_index(index, rules))
        for index in indexes
        if not ("backing_indexes" in rules and index.backs_constraint) or index.name in declared
    ]


def _parity_index(index: Index, rules: frozenset[str]) -> Index:
    expressions = "analysed_expressions" in rules
    generated = "generated_names" in rules and _generated_index_name(index.table.name, index.name)
    return replace(
        index,
        name=None if generated else index.name,
        table=_parity_relation(index.table, rules),
        columns=tuple(
            key if not expressions or _COLUMN_KEY.fullmatch(key) else _EXPRESSION
            for key in index.columns
        ),
        where=_expression(index.where, rules),
    )


def _in_order[T](objects: list[T], rules: frozenset[str]) -> tuple[T, ...]:
    return tuple(sorted(objects, key=repr) if "declaration_order" in rules else objects)


def _parity_table(table: Table, rules: frozenset[str]) -> Table:
    return replace(
        table,
        schema=_fold_schema(table.schema, rules),
        columns=tuple(parity_column(c, rules) for c in table.columns),
        constraints=_in_order(
            [parity_constraint(table.name, c, rules) for c in table.constraints], rules
        ),
        indexes=_in_order([seen for _, seen in parity_indexes(table.indexes, rules)], rules),
    )


def parity_routine(routine: Routine, rules: frozenset[str] = ALL_PARITY_RULES) -> Routine:
    """*routine* as *rules* compare it: identity by ``signature_key``, never its spelling."""
    routine = replace(routine, schema=_fold_schema(routine.schema, rules))
    if "routine_spellings" not in rules:
        return routine
    return replace(routine, signature="", returns=None)


def parity_view(view: View, rules: frozenset[str] = ALL_PARITY_RULES) -> View:
    """*view* as *rules* compare it: that its query exists, and its own indexes."""
    definition = view.definition
    if definition is not None and "view_definitions" in rules:
        definition = _EXPRESSION
    return replace(
        view,
        schema=_fold_schema(view.schema, rules),
        definition=definition,
        indexes=_in_order([seen for _, seen in parity_indexes(view.indexes, rules)], rules),
    )


#: The fillfactor a stock pg_tviews creates a TVIEW with (``pg_tviews.fillfactor``);
#: ``pg_tviews.unlogged_by_default`` is on, so it is created unlogged.
_TVIEW_DEFAULT_FILLFACTOR = 85


def parity_tview(tview: TView, rules: frozenset[str] = ALL_PARITY_RULES) -> TView:
    """*tview* as *rules* compare it: an option pg_tviews chose by default is no pin."""
    tview = replace(tview, schema=_fold_schema(tview.schema, rules))
    if "tview_defaults" not in rules:
        return tview
    return replace(
        tview,
        logged=True if tview.logged else None,
        fillfactor=None if tview.fillfactor == _TVIEW_DEFAULT_FILLFACTOR else tview.fillfactor,
    )


def _parity_sequence(sequence: Sequence, rules: frozenset[str]) -> Sequence:
    sequence = replace(sequence, schema=_fold_schema(sequence.schema, rules))
    unbounded = sequence.min_value in (None, 1) and (
        sequence.max_value is None or sequence.max_value in _DEFAULT_MAX
    )
    if "sequence_bounds" not in rules or not unbounded:
        return sequence
    return replace(sequence, min_value=None, max_value=None)


def normalise_for_parity(
    model: SchemaModel, rules: frozenset[str] = ALL_PARITY_RULES
) -> SchemaModel:
    """*model* with the rewrites in *rules* — every one of :data:`PARITY_NORMALISATIONS` by default.

    Applied to both sides of a parse/live comparison; what still differs after it
    is a difference between the tree and the database, or a bug in a reader. The
    differ applies the same rules, object by object, when it compares a tree with
    a database (``differ.CATALOGUED``).
    """
    return SchemaModel(
        coverage=model.coverage,
        source=model.source,
        tables={ref: _parity_table(t, rules) for ref, t in model.tables.items()},
        enum_types={
            ref: replace(e, schema=_fold_schema(e.schema, rules))
            for ref, e in model.enum_types.items()
        },
        sequences={ref: _parity_sequence(s, rules) for ref, s in model.sequences.items()},
        routines={
            ref: tuple(parity_routine(r, rules) for r in found)
            for ref, found in model.routines.items()
        },
        views={ref: parity_view(v, rules) for ref, v in model.views.items()},
        triggers={
            ref: replace(t, schema=_fold_schema(t.schema, rules))
            for ref, t in model.triggers.items()
        },
        tviews={ref: parity_tview(t, rules) for ref, t in model.tviews.items()},
        other_objects=model.other_objects,
    )
