"""Seed generation bridge: generate seed SQL files from schema introspection."""

from __future__ import annotations

import dataclasses
from pathlib import Path
from typing import Any


@dataclasses.dataclass
class SeedGenerationConfig:
    """Configuration for seed generation."""

    table: str
    schema: str = "public"
    row_count: int = 10
    output_dir: Path = dataclasses.field(default_factory=lambda: Path("db/seeds"))
    env: str = "development"
    include_comments: bool = True
    overwrite: bool = False


@dataclasses.dataclass
class SeedGenerationResult:
    """Result of a seed generation operation."""

    table: str
    output_path: Path
    row_count: int
    column_count: int
    success: bool
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a dictionary."""
        return {
            "table": self.table,
            "output_path": str(self.output_path),
            "row_count": self.row_count,
            "column_count": self.column_count,
            "success": self.success,
            "error": self.error,
        }


class SeedBridge:
    """Generates SQL seed files from schema introspection.

    This is a lightweight bridge that generates INSERT-based seed stubs
    from PostgreSQL table structures. For production-grade seed generation
    with anonymization support, see the fraiseql-data package.
    """

    def __init__(
        self,
        database_url: str,
        *,
        fraiseql_data_available: bool | None = None,
    ) -> None:
        self._database_url = database_url
        self._fraiseql_data = fraiseql_data_available

    def _check_fraiseql_data(self) -> bool:
        """Check if fraiseql-data package is available."""
        if self._fraiseql_data is not None:
            return self._fraiseql_data
        try:
            import fraiseql.data  # noqa: F401, PLC0415  # type: ignore[import]

            return True
        except ImportError:
            return False

    def _get_table_columns(self, table: str, schema: str = "public") -> list[dict[str, Any]]:
        """Introspect columns for a given table."""
        import psycopg

        with psycopg.connect(self._database_url) as conn, conn.cursor() as cur:
            cur.execute(
                """
                    SELECT column_name, data_type, is_nullable, column_default
                    FROM information_schema.columns
                    WHERE table_schema = %s AND table_name = %s
                    ORDER BY ordinal_position
                    """,
                (schema, table),
            )
            rows = cur.fetchall()
            return [
                {
                    "name": row[0],
                    "type": row[1],
                    "nullable": row[2] == "YES",
                    "default": row[3],
                }
                for row in rows
            ]

    def _generate_stub_sql(
        self, table: str, columns: list[dict[str, Any]], config: SeedGenerationConfig
    ) -> str:
        """Generate stub INSERT SQL for a table."""
        lines: list[str] = []

        if config.include_comments:
            lines.append(f"-- Seed data for {config.schema}.{table}")
            lines.append("-- Generated by confiture seed generate")
            lines.append(f"-- Rows: {config.row_count}")
            lines.append("")

        col_names = [c["name"] for c in columns if not c.get("default")]
        if not col_names:
            col_names = [c["name"] for c in columns]

        cols_str = ", ".join(col_names)

        lines.append(f"-- INSERT INTO {config.schema}.{table} ({cols_str})")
        lines.append("-- VALUES")
        for i in range(config.row_count):
            values = ", ".join(f"<{c['type']}_{i + 1}>" for c in columns if c["name"] in col_names)
            suffix = ";" if i == config.row_count - 1 else ","
            lines.append(f"--     ({values}){suffix}")

        lines.append("")
        lines.append(
            "-- HINT: Replace placeholder values above with actual data or use a generator."
        )

        return "\n".join(lines)

    def generate(self, config: SeedGenerationConfig) -> SeedGenerationResult:
        """Generate a seed file for a table.

        If fraiseql-data is available, delegates to it for richer generation.
        Otherwise, produces a commented-out stub with correct column names.
        """
        try:
            columns = self._get_table_columns(config.table, config.schema)
        except Exception as e:
            return SeedGenerationResult(
                table=config.table,
                output_path=config.output_dir / f"{config.table}.sql",
                row_count=0,
                column_count=0,
                success=False,
                error=str(e),
            )

        if not columns:
            return SeedGenerationResult(
                table=config.table,
                output_path=config.output_dir / f"{config.table}.sql",
                row_count=0,
                column_count=0,
                success=False,
                error=f"Table {config.schema}.{config.table} not found or has no columns",
            )

        output_dir = config.output_dir / config.env
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{config.table}.sql"

        if output_path.exists() and not config.overwrite:
            return SeedGenerationResult(
                table=config.table,
                output_path=output_path,
                row_count=0,
                column_count=len(columns),
                success=False,
                error=f"File {output_path} already exists. Use --overwrite to replace.",
            )

        sql = self._generate_stub_sql(config.table, columns, config)
        output_path.write_text(sql)

        return SeedGenerationResult(
            table=config.table,
            output_path=output_path,
            row_count=config.row_count,
            column_count=len(columns),
            success=True,
        )
