"""Emitter protocol and EmittedFunction dataclass for scaffold generation.

External generators (framework emitters) implement :class:`ConfitureEmitter`
to produce SQL function content.  :class:`ScaffoldOrchestrator` consumes
the emitted functions and handles file placement.

Example (library usage)::

    from confiture.core.scaffold import ConfitureEmitter, EmittedFunction
    from pathlib import Path

    class MyCRUDEmitter:
        def emit(self) -> list[EmittedFunction]:
            return [
                EmittedFunction(
                    verb="create",
                    subtree=Path("db/schema/functions/catalog"),
                    content="CREATE OR REPLACE FUNCTION ...",
                    generated_marker="-- GENERATED by my-framework v1.0",
                )
            ]
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, runtime_checkable


@dataclass
class EmittedFunction:
    """A single SQL function to be placed in the schema tree.

    Attributes:
        verb: Verb suffix for the output filename, e.g. ``"create"``
            produces ``"<prefix>_create.sql"``.
        subtree: Target directory under the schema root.  May be
            absolute or relative; the orchestrator resolves it.
        content: SQL body to write into the file (everything after the
            generated header).
        generated_marker: First line of the file header, conventionally
            a SQL comment, e.g. ``"-- GENERATED by foo v1.2.3"``.
    """

    verb: str
    subtree: Path
    content: str
    generated_marker: str


@runtime_checkable
class ConfitureEmitter(Protocol):
    """Protocol for framework-specific SQL function emitters.

    Implementations are responsible only for SQL *content* and placement
    intent (:class:`EmittedFunction`).  All tree-management concerns
    (prefix allocation, file writing, override handling) are handled by
    :class:`~confiture.core.scaffold.orchestrator.ScaffoldOrchestrator`.

    To implement::

        class MyEmitter:
            def emit(self) -> list[EmittedFunction]:
                ...

    The callable used with ``confiture generate scaffold --from`` must
    return a list of :class:`EmittedFunction` when invoked with no
    arguments (it may be a function, a bound method, or any callable).
    """

    def emit(self) -> list[EmittedFunction]: ...
