"""Scaffold orchestrator — allocates paths and writes emitted functions.

:class:`ScaffoldOrchestrator` is the engine behind
``confiture generate scaffold``.  It receives a list of
:class:`~confiture.core.scaffold.emitter.EmittedFunction` objects,
allocates sort-stable filenames via :class:`~confiture.core.tree_allocator.TreeAllocator`,
checks for user-owned overrides, and writes files with a ``-- GENERATED``
header.

Override mechanism
------------------
When a user wants to take permanent ownership of a generated file they
move it to a mirror directory (``overrides/`` by default).  On the next
scaffold run the orchestrator sees the override and skips that path,
leaving the user's version untouched.

Example::

    from pathlib import Path
    from confiture.core.scaffold import ScaffoldOrchestrator
    from confiture.core.scaffold.emitter import EmittedFunction

    schema_dir = Path("db/schema")
    orchestrator = ScaffoldOrchestrator(schema_dir, dry_run=True)

    functions = [
        EmittedFunction(
            verb="create",
            subtree=schema_dir / "functions/catalog",
            content="CREATE OR REPLACE FUNCTION ...",
            generated_marker="-- GENERATED by my-framework v1.0",
        )
    ]

    for result in orchestrator.run(functions):
        print(result.action, result.path)
"""

from __future__ import annotations

import dataclasses
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from confiture.core.scaffold.emitter import EmittedFunction
from confiture.core.tree_allocator import TreeAllocator

_OWNERSHIP_NOTE = "-- Do not edit — move to overrides/ to take ownership."


@dataclasses.dataclass
class ScaffoldResult:
    """The outcome of processing a single :class:`~confiture.core.scaffold.emitter.EmittedFunction`.

    Attributes:
        path: Allocated (absolute) path for the file.
        action: ``"write"`` if the file was (or would be) written;
            ``"skip"`` if an override exists and the file was left alone.
    """

    path: Path
    action: Literal["write", "skip"]


class ScaffoldOrchestrator:
    """Allocates filenames and writes SQL files emitted by a framework generator.

    Args:
        schema_dir: Root of the schema tree.  All :attr:`EmittedFunction.subtree`
            values must be within this directory.
        overrides_dir: Mirror directory for user-owned files.  When a file
            at ``overrides_dir / (path relative to schema_dir)`` exists,
            the orchestrator records ``action="skip"`` and writes nothing.
            *None* disables override checking.
        dry_run: When *True*, no files are written to disk.  Results still
            report ``action="write"`` (what *would* happen) or ``"skip"``.
    """

    def __init__(
        self,
        schema_dir: Path,
        overrides_dir: Path | None = None,
        dry_run: bool = False,
    ) -> None:
        self.schema_dir = schema_dir.resolve()
        self.overrides_dir = overrides_dir.resolve() if overrides_dir else None
        self.dry_run = dry_run
        self._allocator = TreeAllocator(self.schema_dir)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self, functions: list[EmittedFunction]) -> list[ScaffoldResult]:
        """Process *functions* and return one :class:`ScaffoldResult` per entry.

        Functions are processed in order.  Each allocated path is
        immediately visible to subsequent allocations in the same call
        (because the allocator re-scans the directory), but files written
        during this run are taken into account only if they actually exist
        on disk (i.e. ``dry_run=False``).

        Args:
            functions: List of functions to scaffold.

        Returns:
            List of :class:`ScaffoldResult` in the same order as *functions*.
        """
        date_str = datetime.now(UTC).isoformat(timespec="seconds")
        results: list[ScaffoldResult] = []

        for fn in functions:
            output_path = self._allocator.alloc(fn.subtree, verb=fn.verb)

            if self._override_exists(output_path):
                results.append(ScaffoldResult(path=output_path, action="skip"))
                continue

            if not self.dry_run:
                self._write_file(output_path, fn.content, fn.generated_marker, date_str)

            results.append(ScaffoldResult(path=output_path, action="write"))

        return results

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _override_exists(self, output_path: Path) -> bool:
        """Return *True* if a matching override file exists."""
        if self.overrides_dir is None:
            return False
        if not self.overrides_dir.exists():
            return False
        try:
            rel = output_path.relative_to(self.schema_dir)
        except ValueError:
            return False
        return (self.overrides_dir / rel).exists()

    @staticmethod
    def _build_content(sql_content: str, marker: str, date_str: str) -> str:
        """Prepend the generated header to *sql_content*."""
        header_lines = [
            marker,
            f"-- Generated on: {date_str}",
            _OWNERSHIP_NOTE,
            "",
        ]
        return "\n".join(header_lines) + "\n" + sql_content

    def _write_file(self, path: Path, content: str, marker: str, date_str: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self._build_content(content, marker, date_str))
