"""The DDL the differ generates for a constraint applies to a real PostgreSQL (#315, #316).

Parsing proves a statement is grammatical. It does not prove PostgreSQL accepts
it — ``ALTER TABLE t ALTER COLUMN id DROP NOT NULL`` parses and is refused on a
primary-key column — and it does not prove the constraint that lands is the one
the schema declared. So this applies the generated migration and asks the
catalogue what it got.

It also pins the claim that makes the unnamed form safe: the name PostgreSQL
generates for a constraint confiture wrote unnamed is the name it would have
generated for the author's own DDL. Confiture never has to invent one.
"""

from __future__ import annotations

import psycopg
import pytest

from confiture.core.differ import SchemaDiffer
from confiture.core.differ_sql import DifferSQLGenerator

BASE = "CREATE SCHEMA b;\nCREATE SCHEMA a;\nCREATE TABLE b.parent (id INT PRIMARY KEY);\n"

#: Columns declared on both sides, so what the migration carries is constraints.
OLD = BASE + "CREATE TABLE a.child (id INT, pid INT, noref INT, u INT, c INT);\n"

#: A typmod on every shape that carries one, to be asked back from the catalogue.
TYPED = BASE + (
    "CREATE TABLE a.typed (code VARCHAR(50), amount NUMERIC(10,2), flag CHAR(2), n INT);\n"
)

NEW = (
    BASE + "CREATE TABLE a.child (\n"
    "  id INT,\n"
    "  pid INT REFERENCES b.parent(id) ON DELETE CASCADE,\n"
    "  noref INT REFERENCES b.parent,\n"
    "  u INT UNIQUE,\n"
    "  c INT CHECK (c > 0),\n"
    "  CONSTRAINT ck_named CHECK (id > 0)\n"
    ");\n"
    "CREATE TABLE a.fresh (\n"
    "  pk INT PRIMARY KEY,\n"
    "  pid INT REFERENCES b.parent(id) ON UPDATE RESTRICT,\n"
    "  u INT UNIQUE,\n"
    "  CONSTRAINT ck CHECK (pk > 0)\n"
    ");\n"
)


def _generated_up() -> str:
    generator = DifferSQLGenerator()
    return "\n".join(
        generator.generate_up(change) for change in SchemaDiffer().compare(OLD, NEW).changes
    )


@pytest.fixture
def migrated(fresh_database: str) -> psycopg.Connection:
    """*OLD* built, then the generated migration applied on top of it."""
    conn = psycopg.connect(fresh_database, autocommit=True)
    conn.execute(OLD)
    conn.execute(_generated_up())
    return conn


def _constraints(conn: psycopg.Connection, table: str) -> dict[str, tuple[str, str]]:
    rows = conn.execute(
        """
        SELECT conname, contype, pg_get_constraintdef(oid)
        FROM pg_constraint
        WHERE conrelid = %s::regclass
        """,
        (table,),
    ).fetchall()
    return {name: (contype, definition) for name, contype, definition in rows}


def test_the_generated_migration_applies(migrated: psycopg.Connection) -> None:
    """The whole point: a statement that parses can still be refused."""
    assert migrated.execute("SELECT 1").fetchone() == (1,)


def test_a_column_level_foreign_key_lands_with_its_action(migrated: psycopg.Connection) -> None:
    found = _constraints(migrated, "a.child")["child_pid_fkey"]
    assert found[0] == "f"
    assert "ON DELETE CASCADE" in found[1]


def test_a_reference_with_no_column_list_resolves_to_the_primary_key(
    migrated: psycopg.Connection,
) -> None:
    assert "REFERENCES b.parent(id)" in _constraints(migrated, "a.child")["child_noref_fkey"][1]


def test_the_unnamed_names_are_the_ones_postgresql_would_have_generated(
    fresh_database: str, migrated: psycopg.Connection
) -> None:
    """Declared directly and generated by confiture, the names agree.

    This is what makes omitting the ``CONSTRAINT`` clause safe rather than lossy:
    a later ``confiture drift`` compares like with like.
    """
    with psycopg.connect(fresh_database, autocommit=True) as direct:
        direct.execute("CREATE SCHEMA declared")
        direct.execute(
            "CREATE TABLE declared.child (id INT, pid INT REFERENCES b.parent(id),"
            " u INT UNIQUE, c INT CHECK (c > 0))"
        )
        # PostgreSQL names a constraint after the *relation*, not the schema, so
        # both tables produce `child_…` names and the sets compare directly.
        declared = set(_constraints(direct, "declared.child"))
    assert declared <= set(_constraints(migrated, "a.child"))


def test_a_new_table_arrives_with_its_constraints(migrated: psycopg.Connection) -> None:
    found = _constraints(migrated, "a.fresh")
    # A superset: PostgreSQL 17 and later also list NOT NULL (`n`) here, and the
    # primary key's column carries one.
    assert {found[name][0] for name in found} >= {"p", "f", "u", "c"}
    assert "ON UPDATE RESTRICT" in found["fresh_pid_fkey"][1]


def test_the_check_constraints_carry_their_predicates(migrated: psycopg.Connection) -> None:
    found = _constraints(migrated, "a.child")
    assert "(id > 0)" in found["ck_named"][1]
    assert "(c > 0)" in found["child_c_check"][1]


def test_a_generated_column_keeps_its_length_and_precision(fresh_database: str) -> None:
    """``VARCHAR(50)`` generated ``VARCHAR`` — an unbounded column where the
    schema said fifty characters. Asked back from ``format_type``, which is
    PostgreSQL's own answer rather than confiture's."""
    generator = DifferSQLGenerator()
    sql = "\n".join(
        generator.generate_up(change) for change in SchemaDiffer().compare(BASE, TYPED).changes
    )
    with psycopg.connect(fresh_database, autocommit=True) as conn:
        conn.execute(BASE)
        conn.execute(sql)
        rows = conn.execute(
            """
            SELECT attname, format_type(atttypid, atttypmod)
            FROM pg_attribute
            WHERE attrelid = 'a.typed'::regclass AND attnum > 0 AND NOT attisdropped
            ORDER BY attnum
            """
        ).fetchall()
    assert rows == [
        ("code", "character varying(50)"),
        ("amount", "numeric(10,2)"),
        ("flag", "character(2)"),
        ("n", "integer"),
    ]
