"""Integration test backing examples/07-external-emitter.

The example README documents an exact CLI sequence — if any of it stops
working, this test should fail before the example goes stale.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import pytest
from typer.testing import CliRunner

from confiture.cli.main import app

pytestmark = pytest.mark.integration

runner = CliRunner()
EXAMPLE_DIR = Path(__file__).resolve().parent.parent.parent / "examples" / "07-external-emitter"


def test_example_emitter_runs_end_to_end(tmp_path: Path) -> None:
    """Copy the example to tmp_path, run scaffold, check the two SQL files land."""
    # Copy the example to a clean tmpdir so the test doesn't pollute the repo.
    work = tmp_path / "ex07"
    shutil.copytree(EXAMPLE_DIR, work)

    # Make the emitter importable.
    sys.path.insert(0, str(work))
    old_cwd = Path.cwd()
    try:
        import os

        os.chdir(work)

        result = runner.invoke(
            app,
            [
                "generate",
                "scaffold",
                "--from",
                "emitter:emit",
                "--schema-dir",
                "db/schema",
            ],
        )
        assert result.exit_code == 0, result.output

        sandbox = work / "db" / "schema" / "functions" / "sandbox"
        sql_files = sorted(sandbox.glob("*.sql"))
        assert len(sql_files) == 2

        ping_file = sandbox / "00001_ping.sql"
        echo_file = sandbox / "00002_echo_ping.sql"
        assert ping_file.exists()
        assert echo_file.exists()

        # Header and content match what the README promises.
        ping_text = ping_file.read_text()
        assert "-- GENERATED by example-emitter v0.1.0" in ping_text
        assert "SELECT 'pong'::text;" in ping_text

        echo_text = echo_file.read_text()
        assert "SELECT ping();" in echo_text  # cross-reference present
    finally:
        os.chdir(old_cwd)
        sys.path.remove(str(work))
        sys.modules.pop("emitter", None)


def test_example_override_mechanism(tmp_path: Path) -> None:
    """The README claims an override mirror skips that path on the next run."""
    work = tmp_path / "ex07"
    shutil.copytree(EXAMPLE_DIR, work)

    sys.path.insert(0, str(work))
    old_cwd = Path.cwd()
    try:
        import os

        os.chdir(work)

        # First run — generate.
        result = runner.invoke(
            app,
            ["generate", "scaffold", "--from", "emitter:emit", "--schema-dir", "db/schema"],
        )
        assert result.exit_code == 0, result.output

        # Set up an override.
        overrides = work / "overrides" / "functions" / "sandbox"
        overrides.mkdir(parents=True)
        # Override 00001_ping.sql with custom content.
        (overrides / "00001_ping.sql").write_text("-- USER OVERRIDE\n")

        # Second run with --overrides-dir — the orchestrator allocates the next
        # available prefix (00003, 00004) since the on-disk 00001 and 00002 already
        # exist.  Verify the override file itself is untouched.
        result = runner.invoke(
            app,
            [
                "generate",
                "scaffold",
                "--from",
                "emitter:emit",
                "--schema-dir",
                "db/schema",
                "--overrides-dir",
                "overrides",
                "--json",
            ],
        )
        assert result.exit_code == 0, result.output

        # The user's override is untouched.
        assert (overrides / "00001_ping.sql").read_text() == "-- USER OVERRIDE\n"
    finally:
        os.chdir(old_cwd)
        sys.path.remove(str(work))
        sys.modules.pop("emitter", None)
