"""End-to-end integration test for the ``confiture generate`` command tree.

Walks through the full workflow as a user would: ``alloc`` → ``scaffold``
(via an in-test emitter module) → file on disk → ``renumber`` → references
rewritten.  No database connection required.

Issue #111 success criterion: this test guards the CLI wiring between
``alloc``, ``scaffold``, ``renumber``, and the cross-repo refusal feature.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest
from typer.testing import CliRunner

from confiture.cli.main import app

pytestmark = pytest.mark.integration

runner = CliRunner()


@pytest.fixture
def project(tmp_path: Path):
    """A minimal project layout: tmp_path/repo/db/schema/functions/."""
    repo = tmp_path / "repo"
    schema = repo / "db" / "schema"
    funcs = schema / "functions"
    funcs.mkdir(parents=True)
    return {"repo": repo, "schema": schema, "funcs": funcs}


def test_alloc_returns_next_filename_in_empty_dir(project) -> None:
    result = runner.invoke(
        app,
        [
            "generate",
            "alloc",
            str(project["funcs"]),
            "--schema-dir",
            str(project["schema"]),
            "--verb",
            "create_item",
            "--json",
        ],
    )
    assert result.exit_code == 0, result.output
    payload = json.loads(result.stdout)
    assert payload["path"].endswith("_create_item.sql")
    assert "00001" in Path(payload["path"]).name


def test_alloc_rejects_unsafe_verb(project) -> None:
    """The security fix from Phase 02 Cycle 2 must surface through the CLI."""
    result = runner.invoke(
        app,
        [
            "generate",
            "alloc",
            str(project["funcs"]),
            "--schema-dir",
            str(project["schema"]),
            "--verb",
            "../escape",
        ],
    )
    assert result.exit_code != 0
    assert "verb" in result.output


def test_scaffold_then_renumber_full_flow(project, tmp_path: Path) -> None:
    """alloc → scaffold (via emitter) → file on disk → renumber → ref rewritten."""
    # 1. Write a tiny emitter module on disk; importable via sys.path.
    emitter_mod = tmp_path / "emitter_for_test.py"
    funcs_abs = project["funcs"].resolve()
    emitter_mod.write_text(
        "from pathlib import Path\n"
        "from confiture.core.scaffold.emitter import EmittedFunction\n"
        "\n"
        "def emit():\n"
        "    return [\n"
        "        EmittedFunction(\n"
        '            verb="create_item",\n'
        f"            subtree=Path({str(funcs_abs)!r}),\n"
        '            content="CREATE OR REPLACE FUNCTION create_item() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;",\n'
        '            generated_marker="-- GENERATED by test-emitter",\n'
        "        ),\n"
        "        EmittedFunction(\n"
        '            verb="update_item",\n'
        f"            subtree=Path({str(funcs_abs)!r}),\n"
        '            content="CREATE OR REPLACE FUNCTION update_item() RETURNS void AS $$ BEGIN PERFORM create_item(); END; $$ LANGUAGE plpgsql;",\n'
        '            generated_marker="-- GENERATED by test-emitter",\n'
        "        ),\n"
        "    ]\n"
    )

    # Make it importable.
    sys.path.insert(0, str(tmp_path))
    try:
        # 2. Run scaffold.
        result = runner.invoke(
            app,
            [
                "generate",
                "scaffold",
                "--from",
                "emitter_for_test:emit",
                "--schema-dir",
                str(project["schema"]),
                "--json",
            ],
        )
        assert result.exit_code == 0, result.output
        payload = json.loads(result.stdout)
        assert len(payload["results"]) == 2
        create_path = Path(payload["results"][0]["path"])
        update_path = Path(payload["results"][1]["path"])
        assert create_path.exists()
        assert update_path.exists()
        # Confirm the cross-reference is present (update_item calls create_item).
        assert "create_item()" in update_path.read_text()

        # 3. Renumber create_item to a different verb (force a name change to test rewrite).
        new_path = project["funcs"] / "00099_make_item.sql"
        result = runner.invoke(
            app,
            [
                "generate",
                "renumber",
                str(create_path),
                str(new_path),
                "--schema-dir",
                str(project["schema"]),
                "--json",
            ],
        )
        assert result.exit_code == 0, result.output
        renum = json.loads(result.stdout)
        assert len(renum["moves"]) == 1
        assert renum["moves"][0]["old"] == str(create_path.resolve())
        assert renum["moves"][0]["new"] == str(new_path.resolve())
        # The update_item file should have been rewritten.
        rewrites = [rw for rw in renum["ref_rewrites"] if rw["old_name"] != rw["new_name"]]
        assert len(rewrites) == 1
        assert rewrites[0]["new_name"] == "make_item"
        assert "make_item()" in update_path.read_text()
        assert "create_item()" not in update_path.read_text()
    finally:
        sys.path.remove(str(tmp_path))
        # Wipe the cached module so subsequent test runs see fresh source.
        sys.modules.pop("emitter_for_test", None)


def test_renumber_refuses_when_filename_referenced_outside_db(project, tmp_path: Path) -> None:
    """The cross-repo refusal from Phase 02 Cycle 3 must trip through the CLI."""
    old = project["funcs"] / "00001_create_item.sql"
    old.write_text("-- defines create_item")
    new = project["funcs"] / "00005_create_item.sql"

    # Add app code outside db/ referencing the filename literally.
    (project["repo"] / "app").mkdir()
    (project["repo"] / "app" / "loader.py").write_text(
        'SQL = "db/schema/functions/00001_create_item.sql"\n'
    )

    # Run from inside the repo so git rev-parse (or the fs fallback) sees the project.
    old_cwd = Path.cwd()
    try:
        os.chdir(project["repo"])
        result = runner.invoke(
            app,
            [
                "generate",
                "renumber",
                str(old),
                str(new),
                "--schema-dir",
                str(project["schema"]),
            ],
        )
        assert result.exit_code != 0
        assert "referenced outside" in result.output or "loader.py" in result.output

        # --force lets it through.
        result = runner.invoke(
            app,
            [
                "generate",
                "renumber",
                str(old),
                str(new),
                "--schema-dir",
                str(project["schema"]),
                "--force",
            ],
        )
        assert result.exit_code == 0, result.output
        assert not old.exists()
        assert new.exists()
    finally:
        os.chdir(old_cwd)
