"""Integration test backing examples/07-external-emitter.

The example README documents an exact CLI sequence — if any of it stops
working, this test should fail before the example goes stale.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

import pytest
from typer.testing import CliRunner

from confiture.cli.main import app

pytestmark = pytest.mark.integration

runner = CliRunner()
EXAMPLE_DIR = Path(__file__).resolve().parent.parent.parent / "examples" / "07-external-emitter"


def test_example_emitter_runs_end_to_end(tmp_path: Path) -> None:
    """Copy the example to tmp_path, run scaffold, check the two SQL files land."""
    # Copy the example to a clean tmpdir so the test doesn't pollute the repo.
    work = tmp_path / "ex07"
    shutil.copytree(EXAMPLE_DIR, work)

    # Make the emitter importable.
    sys.path.insert(0, str(work))
    old_cwd = Path.cwd()
    try:
        import os

        os.chdir(work)

        result = runner.invoke(
            app,
            [
                "generate",
                "scaffold",
                "--from",
                "emitter:emit",
                "--schema-dir",
                "db/schema",
            ],
        )
        assert result.exit_code == 0, result.output

        sandbox = work / "db" / "schema" / "functions" / "sandbox"
        sql_files = sorted(sandbox.glob("*.sql"))
        assert len(sql_files) == 2

        ping_file = sandbox / "00001_ping.sql"
        echo_file = sandbox / "00002_echo_ping.sql"
        assert ping_file.exists()
        assert echo_file.exists()

        # Header and content match what the README promises.
        ping_text = ping_file.read_text()
        assert "-- GENERATED by example-emitter v0.1.0" in ping_text
        assert "SELECT 'pong'::text;" in ping_text

        echo_text = echo_file.read_text()
        assert "SELECT ping();" in echo_text  # cross-reference present
    finally:
        os.chdir(old_cwd)
        sys.path.remove(str(work))
        sys.modules.pop("emitter", None)


def test_example_override_mechanism_skips_overridden_path(tmp_path: Path) -> None:
    """When an override exists at the path the orchestrator would allocate,
    scaffold reports ``skip`` and does NOT write that path in db/schema/.

    The override mechanism matches by *allocated path*, so the workflow that
    exercises it is wipe-then-regen: the user clears db/schema/functions/sandbox/
    before each run, ensures any files they own live in overrides/, and
    scaffold writes only the non-overridden paths.
    """
    import json

    work = tmp_path / "ex07"
    shutil.copytree(EXAMPLE_DIR, work)

    sys.path.insert(0, str(work))
    old_cwd = Path.cwd()
    try:
        import os

        os.chdir(work)

        # Set up an override BEFORE the first scaffold so the allocator's
        # first-allocated path (00001_ping.sql) hits the override.
        overrides = work / "overrides" / "functions" / "sandbox"
        overrides.mkdir(parents=True)
        (overrides / "00001_ping.sql").write_text("-- USER OVERRIDE\n")

        # Run with --overrides-dir against an empty schema dir.
        result = runner.invoke(
            app,
            [
                "generate",
                "scaffold",
                "--from",
                "emitter:emit",
                "--schema-dir",
                "db/schema",
                "--overrides-dir",
                "overrides",
                "--json",
            ],
        )
        assert result.exit_code == 0, result.output
        payload = json.loads(result.stdout)

        # Two results: 00001_ping.sql skipped (overridden), an echo_ping file written.
        # Note: because the skip didn't write to disk, the allocator's next call
        # still sees an empty dir and allocates 00001_ — for the second function.
        # The skipped path is unique by verb (ping), the written path is the next
        # available numeric prefix in an otherwise-empty dir.
        assert len(payload["results"]) == 2
        skipped = [r for r in payload["results"] if r["action"] == "skip"]
        written = [r for r in payload["results"] if r["action"] == "write"]
        assert len(skipped) == 1, payload
        assert len(written) == 1, payload
        assert "_ping.sql" in skipped[0]["path"]
        assert "_echo_ping.sql" in written[0]["path"]

        # On disk: the skipped path must NOT exist in db/schema/; the override file
        # is untouched; the echo file landed under db/schema/.
        sandbox = work / "db" / "schema" / "functions" / "sandbox"
        assert not (sandbox / "00001_ping.sql").exists(), (
            "Override mechanism failed: scaffold wrote a file the override should have skipped."
        )
        assert (overrides / "00001_ping.sql").read_text() == "-- USER OVERRIDE\n"
        echo_files = list(sandbox.glob("*_echo_ping.sql"))
        assert len(echo_files) == 1, f"Expected one echo file, got: {echo_files}"
    finally:
        os.chdir(old_cwd)
        sys.path.remove(str(work))
        sys.modules.pop("emitter", None)
