"""Unit tests for `confiture generate scaffold` CLI command.

Uses Typer's CliRunner and unittest.mock to avoid real emitter loading.
No database required.
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from typer.testing import CliRunner

from confiture.cli.main import app
from confiture.core.scaffold.emitter import EmittedFunction

runner = CliRunner()

_MOCK_PATH = "confiture.cli.generate._load_emitter_callable"


def _make_schema(tmp_path: Path) -> tuple[Path, Path]:
    schema = tmp_path / "schema"
    funcs = schema / "functions"
    funcs.mkdir(parents=True)
    return schema, funcs


def _stub_emitter(funcs: Path, verb: str = "create") -> list[EmittedFunction]:
    return [
        EmittedFunction(
            verb=verb,
            subtree=funcs,
            content="SELECT 1;",
            generated_marker="-- GENERATED by stub v0.0",
        )
    ]


# ---------------------------------------------------------------------------
# Happy paths
# ---------------------------------------------------------------------------


class TestScaffoldHappyPath:
    def test_writes_file_when_called(self, tmp_path: Path) -> None:
        schema, funcs = _make_schema(tmp_path)

        with patch(_MOCK_PATH, return_value=lambda: _stub_emitter(funcs)):
            result = runner.invoke(
                app,
                [
                    "generate",
                    "scaffold",
                    "--from",
                    "stub:emit",
                    "--schema-dir",
                    str(schema),
                ],
            )

        assert result.exit_code == 0
        written = list(funcs.glob("*.sql"))
        assert len(written) == 1

    def test_dry_run_writes_nothing(self, tmp_path: Path) -> None:
        schema, funcs = _make_schema(tmp_path)

        with patch(_MOCK_PATH, return_value=lambda: _stub_emitter(funcs)):
            result = runner.invoke(
                app,
                [
                    "generate",
                    "scaffold",
                    "--from",
                    "stub:emit",
                    "--schema-dir",
                    str(schema),
                    "--dry-run",
                ],
            )

        assert result.exit_code == 0
        assert not any(funcs.iterdir())

    def test_dry_run_mentions_would_write(self, tmp_path: Path) -> None:
        schema, funcs = _make_schema(tmp_path)

        with patch(_MOCK_PATH, return_value=lambda: _stub_emitter(funcs)):
            result = runner.invoke(
                app,
                [
                    "generate",
                    "scaffold",
                    "--from",
                    "stub:emit",
                    "--schema-dir",
                    str(schema),
                    "--dry-run",
                ],
            )

        assert "write" in result.stdout.lower() or "dry" in result.stdout.lower()

    def test_json_output_structure(self, tmp_path: Path) -> None:
        schema, funcs = _make_schema(tmp_path)

        with patch(_MOCK_PATH, return_value=lambda: _stub_emitter(funcs)):
            result = runner.invoke(
                app,
                [
                    "generate",
                    "scaffold",
                    "--from",
                    "stub:emit",
                    "--schema-dir",
                    str(schema),
                    "--json",
                ],
            )

        assert result.exit_code == 0
        data = json.loads(result.stdout)
        assert "results" in data
        assert isinstance(data["results"], list)
        assert data["results"][0]["action"] in ("write", "skip")
        assert "path" in data["results"][0]

    def test_json_dry_run_action_is_write(self, tmp_path: Path) -> None:
        schema, funcs = _make_schema(tmp_path)

        with patch(_MOCK_PATH, return_value=lambda: _stub_emitter(funcs)):
            result = runner.invoke(
                app,
                [
                    "generate",
                    "scaffold",
                    "--from",
                    "stub:emit",
                    "--schema-dir",
                    str(schema),
                    "--dry-run",
                    "--json",
                ],
            )

        data = json.loads(result.stdout)
        assert data["results"][0]["action"] == "write"

    def test_skip_reported_for_override(self, tmp_path: Path) -> None:
        schema, funcs = _make_schema(tmp_path)
        overrides = tmp_path / "overrides"
        (overrides / "functions").mkdir(parents=True)
        (overrides / "functions" / "00001_create.sql").write_text("-- mine")

        with patch(_MOCK_PATH, return_value=lambda: _stub_emitter(funcs)):
            result = runner.invoke(
                app,
                [
                    "generate",
                    "scaffold",
                    "--from",
                    "stub:emit",
                    "--schema-dir",
                    str(schema),
                    "--overrides-dir",
                    str(overrides),
                    "--json",
                ],
            )

        data = json.loads(result.stdout)
        assert data["results"][0]["action"] == "skip"


# ---------------------------------------------------------------------------
# Error paths
# ---------------------------------------------------------------------------


class TestScaffoldErrorPaths:
    def test_invalid_from_format_is_config_error(self, tmp_path: Path) -> None:
        schema, _ = _make_schema(tmp_path)

        result = runner.invoke(
            app,
            [
                "generate",
                "scaffold",
                "--from",
                "no-colon-here",
                "--schema-dir",
                str(schema),
            ],
        )

        # Bad --from spec → ConfigurationError → exit 5 (was 1).
        assert result.exit_code == 5

    def test_unimportable_module_is_config_error(self, tmp_path: Path) -> None:
        schema, _ = _make_schema(tmp_path)

        with patch(_MOCK_PATH, side_effect=ValueError("Cannot import")):
            result = runner.invoke(
                app,
                [
                    "generate",
                    "scaffold",
                    "--from",
                    "no.such.module:emit",
                    "--schema-dir",
                    str(schema),
                ],
            )

        assert result.exit_code == 5
