"""One schema source, and every result model validates against it (Phase 06, ENG-10).

Two schema sets used to drift apart: seventeen hand-coded "model" schemas under
``python/confiture/schemas/`` (which rejected real ``migrate up`` output — no
``pending``, no ``skipped_superuser``) and the hand-written CLI schemas under
``docs/reference/json-schemas/``. The packaged directory is the source now, the
docs directory is a generated byte-identical copy, and for every result model a
fully populated ``to_dict()`` validates against the schema its command publishes.
"""

from __future__ import annotations

import dataclasses
import enum
import filecmp
import importlib
import json
import types
import typing
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest
from jsonschema import Draft202012Validator
from referencing import Registry, Resource
from referencing.jsonschema import DRAFT202012

import confiture
from confiture.core import schema_exporter

REPO = Path(__file__).resolve().parents[3]
PACKAGE_SCHEMAS = Path(confiture.__file__).resolve().parent / "schemas"
DOCS_SCHEMAS = REPO / "docs" / "reference" / "json-schemas"
# The CLI layer adds these to every payload; the models do not carry them.
ENVELOPE_KEYS = {"hints": [], "parser": {"pglast": "8.4", "pg_major": 18}}


def _sample(tp: Any, depth: int = 0) -> Any:
    """A fully populated sample value for a type hint (Optional → populated)."""
    origin = typing.get_origin(tp)
    args = typing.get_args(tp)
    if origin in (typing.Union, types.UnionType):
        real = [a for a in args if a is not type(None)]
        if any(isinstance(a, type) and issubclass(a, BaseException) for a in real):
            return None
        return _sample(real[0], depth)
    if tp is Any or tp is object:
        return "x"
    if tp is str:
        return "x"
    if tp is bool:
        return True
    if tp is int:
        return 1
    if tp is float:
        return 1.5
    if tp is datetime:
        return datetime(2026, 9, 6, 12, 0, tzinfo=UTC)
    if tp is Path:
        return Path("x")
    if origin in (list, tuple, set, frozenset):
        inner = _sample(args[0], depth + 1) if args else "x"
        return (
            [inner]
            if origin is list
            else ([inner] if origin is tuple else {inner} if inner.__hash__ else [inner])
        )
    if origin is dict:
        return {"k": _sample(args[1], depth + 1)} if len(args) == 2 else {"k": "x"}
    if origin is typing.Literal:
        return args[0]
    if isinstance(tp, type) and issubclass(tp, enum.Enum):
        return next(iter(tp))
    if dataclasses.is_dataclass(tp):
        return populate(tp, depth + 1)
    return "x"


# Names the models annotate under ``if TYPE_CHECKING:`` only.
_TYPE_ONLY = {"VerifyResult": "confiture.core.migration_verifier"}


def _hints(cls: type) -> dict[str, Any]:
    localns: dict[str, Any] = {}
    for _ in range(3):
        try:
            return typing.get_type_hints(cls, localns=localns)
        except NameError as exc:  # a TYPE_CHECKING-only name
            name = str(exc).split("'")[1]
            localns[name] = getattr(importlib.import_module(_TYPE_ONLY[name]), name)
    return typing.get_type_hints(cls, localns=localns)


# Plain ``str`` fields whose schema constrains the value; the model keeps ``str``
# because its producers build the value from tables, not from a Literal.
FIELD_SAMPLES: dict[tuple[str, str], Any] = {
    ("PreflightIssue", "severity"): "warning",
}


def populate(cls: type, depth: int = 0) -> Any:
    hints = _hints(cls)
    kwargs = {
        f.name: FIELD_SAMPLES.get((cls.__name__, f.name), _sample(hints[f.name], depth))
        for f in dataclasses.fields(cls)
        if f.init
    }
    return cls(**kwargs)


def _registry() -> Registry:
    resources = []
    for path in PACKAGE_SCHEMAS.glob("*.schema.json"):
        schema = json.loads(path.read_text(encoding="utf-8"))
        resources.append(
            (path.name, Resource.from_contents(schema, default_specification=DRAFT202012))
        )
    return Registry().with_resources(resources)


def _validator(filename: str) -> Draft202012Validator:
    schema = json.loads((PACKAGE_SCHEMAS / filename).read_text(encoding="utf-8"))
    return Draft202012Validator(schema, registry=_registry())


def test_package_and_docs_schema_directories_are_identical() -> None:
    package = sorted(p.name for p in PACKAGE_SCHEMAS.glob("*.json"))
    docs = sorted(p.name for p in DOCS_SCHEMAS.glob("*.json"))
    assert package == docs, {
        "only_in_package": set(package) - set(docs),
        "only_in_docs": set(docs) - set(package),
    }
    differing = [
        n for n in package if not filecmp.cmp(PACKAGE_SCHEMAS / n, DOCS_SCHEMAS / n, shallow=False)
    ]
    assert differing == [], f"docs copy is stale: {differing} — run scripts/gen_schemas.py"


@pytest.mark.parametrize(
    ("model_name", "schema_file"),
    sorted(schema_exporter.MODEL_SCHEMAS.items()),
    ids=lambda x: x if x.endswith(".json") else x,
)
def test_populated_model_validates_against_its_schema(model_name: str, schema_file: str) -> None:
    model = schema_exporter.model_class(model_name)
    instance = populate(model)
    declared = _validator(schema_file).schema.get("properties", {})
    extras = {k: v for k, v in ENVELOPE_KEYS.items() if k in declared}
    payload = json.loads(
        json.dumps({**schema_exporter.payload_of(instance), **extras}, default=str)
    )
    errors = sorted(_validator(schema_file).iter_errors(payload), key=lambda e: list(e.path))
    assert errors == [], f"{model_name} → {schema_file}:\n  " + "\n  ".join(
        e.message for e in errors[:8]
    )


def test_every_public_schema_is_mapped_to_a_model_or_listed_as_cli_built() -> None:
    """A schema without a model behind it is a hand-maintained contract; say so explicitly."""
    public = {p.name for p in PACKAGE_SCHEMAS.glob("*.schema.json") if not p.name.startswith("_")}
    covered = set(schema_exporter.MODEL_SCHEMAS.values()) | set(schema_exporter.CLI_BUILT_SCHEMAS)
    assert public == covered, {"unmapped": public - covered, "unknown": covered - public}
