-- Generated by fraiseql compile --emit-ddl
-- Type: Post

CREATE TABLE IF NOT EXISTS tb_post (
    id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    score DOUBLE PRECISION
);
