-- Generated by fraiseql compile --emit-ddl
-- Type: User

CREATE TABLE IF NOT EXISTS tb_user (
    id INTEGER NOT NULL,
    email TEXT NOT NULL,
    display_name TEXT,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
