"""Where a column's value comes from: one answer, read from the parse tree, once.

``writable_columns`` (what a seed writer supplies), parity (what a ``serial``
becomes in the catalog), drift (whose default is its own) and ``tenant_005``
(which keys cannot collide) all ask it. Each used to answer for itself — two of
them by matching ``nextval(`` in text.
"""

from __future__ import annotations

import pytest

from confiture.core.schema_model import ValueSource
from confiture.core.schema_read import read_text

SHAPES = [
    ("id bigint GENERATED ALWAYS AS IDENTITY", ValueSource.IDENTITY),
    ("id bigint GENERATED BY DEFAULT AS IDENTITY", ValueSource.IDENTITY),
    ("total numeric GENERATED ALWAYS AS (1 + 2) STORED", ValueSource.GENERATED),
    ("id serial", ValueSource.SEQUENCE),
    ("id bigserial", ValueSource.SEQUENCE),
    ("id smallserial", ValueSource.SEQUENCE),
    ("id bigint DEFAULT nextval('s'::regclass)", ValueSource.SEQUENCE),
    ("id bigint DEFAULT nextval('app.s')", ValueSource.SEQUENCE),
    ("id uuid DEFAULT gen_random_uuid()", ValueSource.GENERATOR),
    ("id uuid DEFAULT public.gen_random_uuid()", ValueSource.GENERATOR),
    ("id uuid DEFAULT pg_catalog.gen_random_uuid()", ValueSource.GENERATOR),
    ("id uuid DEFAULT uuidv7()", ValueSource.GENERATOR),
    ("id uuid DEFAULT uuid_generate_v4()", ValueSource.GENERATOR),
    ("at timestamptz DEFAULT now()", ValueSource.EXPRESSION),
    ("label text DEFAULT 'x'", ValueSource.CONSTANT),
    ("n int DEFAULT -1", ValueSource.CONSTANT),
    ("flag boolean DEFAULT true", ValueSource.CONSTANT),
    ("doc jsonb DEFAULT '{}'::jsonb", ValueSource.CONSTANT),
    ("label text", ValueSource.NONE),
]


@pytest.mark.parametrize(("column", "source"), SHAPES, ids=[c for c, _ in SHAPES])
def test_a_column_s_value_comes_from_where_its_declaration_says(
    column: str, source: ValueSource
) -> None:
    (table,) = read_text(f"CREATE TABLE app.t ({column});\n").model.tables.values()
    assert table.columns[0].value_source is source


def test_an_alter_that_sets_a_default_sets_where_the_value_comes_from() -> None:
    sql = (
        "CREATE TABLE app.t (id uuid);\n"
        "ALTER TABLE app.t ALTER COLUMN id SET DEFAULT gen_random_uuid();\n"
    )
    (table,) = read_text(sql).model.tables.values()
    assert table.columns[0].value_source is ValueSource.GENERATOR


def test_an_inheritance_child_does_not_inherit_an_identity() -> None:
    sql = (
        "CREATE TABLE app.p (id bigint GENERATED ALWAYS AS IDENTITY, n serial);\n"
        "CREATE TABLE app.c () INHERITS (app.p);\n"
    )
    child = read_text(sql).catalogued.tables
    (table,) = [t for t in child.values() if t.name == "c"]
    assert {c.name: c.value_source for c in table.columns} == {
        "id": ValueSource.NONE,
        "n": ValueSource.SEQUENCE,
    }


@pytest.mark.parametrize(
    ("source", "filled", "unique"),
    [
        (ValueSource.IDENTITY, True, True),
        (ValueSource.GENERATED, True, False),
        (ValueSource.SEQUENCE, True, True),
        (ValueSource.GENERATOR, False, True),
        (ValueSource.EXPRESSION, False, False),
        (ValueSource.CONSTANT, False, False),
        (ValueSource.NONE, False, False),
    ],
)
def test_the_two_questions_are_kept_apart(source: ValueSource, filled: bool, unique: bool) -> None:
    # A generator fills the value only when the writer leaves it out: the
    # writer may still supply it, so it is writable — and unique either way.
    assert (source.filled_by_postgresql, source.unique_without_author_input) == (filled, unique)
