"""What a writer may supply to a table, and what each column it supplies must respect.

A seed generator inserts ``id`` and never ``pk_language``: PostgreSQL fills an
identity, a generated column and a ``serial``'s ``nextval`` default, and a value
written there is either refused or silently replaced. For the columns it does
write, it needs what the schema promises about each — the type, NOT NULL, the
default, uniqueness wherever it was declared, the CHECKs that name the column,
an enum's labels, and the row a foreign key points at, found the way PostgreSQL
found it rather than as the DDL spelled it.
"""

from __future__ import annotations

import pytest

from confiture import platform

DDL = """
CREATE TYPE app.status_enum AS ENUM ('new', 'active', 'retired');
CREATE TABLE other.parent (pk_parent BIGINT PRIMARY KEY, id UUID);
CREATE TABLE app.t (
    pk_x BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id UUID UNIQUE NOT NULL,
    identifier VARCHAR(20) UNIQUE,
    status app.status_enum NOT NULL DEFAULT 'new',
    fk_parent BIGINT REFERENCES other.parent (pk_parent),
    computed INT GENERATED ALWAYS AS (1) STORED,
    created_at TIMESTAMPTZ DEFAULT now(),
    n INT CHECK (n > 0),
    counter SERIAL,
    CHECK (n < 10 AND identifier <> '')
);
CREATE UNIQUE INDEX ux_t_created ON app.t (created_at);
"""


@pytest.fixture(scope="module")
def model() -> platform.SchemaModel:
    return platform.parse_schema(DDL)


def test_postgresql_fills_identity_generated_and_serial_columns(model) -> None:
    names = [c.name for c in platform.writable_columns(model, "app.t")]
    assert names == ["id", "identifier", "status", "fk_parent", "created_at", "n"]


def test_a_nextval_default_is_postgresqls_to_fill() -> None:
    """What the catalog holds for a ``serial``: an integer and a ``nextval`` default."""
    model = platform.parse_schema(
        "CREATE SEQUENCE t_id_seq;\n"
        "CREATE TABLE t (id INT NOT NULL DEFAULT nextval('t_id_seq'::regclass), v TEXT);"
    )
    assert [c.name for c in platform.writable_columns(model, "t")] == ["v"]


def test_an_enum_column_lists_its_labels(model) -> None:
    facts = platform.column_facts(model, "app.t", "status")
    assert facts.enum_values == ("new", "active", "retired")
    assert (facts.not_null, facts.default) == (True, "'new'")
    assert platform.column_facts(model, "app.t", "n").enum_values is None


def test_a_foreign_key_resolves_to_its_table_and_column(model) -> None:
    facts = platform.column_facts(model, "app.t", "fk_parent")
    assert facts.foreign_key == platform.ColumnReference(
        table=next(ref for ref in model.tables if ref.name == "parent"), column="pk_parent"
    )
    assert (facts.foreign_key.table.schema, facts.foreign_key.table.name) == ("other", "parent")


def test_an_unqualified_target_search_path_placed_resolves_to_its_schema() -> None:
    model = platform.parse_schema(
        "CREATE TABLE other.parent (pk_parent BIGINT PRIMARY KEY);\n"
        "CREATE TABLE app.t (fk_parent BIGINT REFERENCES parent);"
    )
    reference = platform.column_facts(model, "app.t", "fk_parent").foreign_key
    assert reference is not None
    assert (reference.table.schema, reference.table.name, reference.column) == (
        "other",
        "parent",
        "pk_parent",
    )


def test_a_target_outside_the_model_is_named_by_the_identity_rule() -> None:
    model = platform.parse_schema("CREATE TABLE t (p INT REFERENCES parent);")
    reference = platform.column_facts(model, "t", "p").foreign_key
    assert reference is not None
    assert (reference.table.schema, reference.table.name, reference.column) == (
        "public",
        "parent",
        None,
    )


def test_a_composite_foreign_key_maps_each_column_to_its_counterpart() -> None:
    model = platform.parse_schema(
        "CREATE TABLE p (a INT, b INT, PRIMARY KEY (a, b));\n"
        "CREATE TABLE c (x INT, y INT, FOREIGN KEY (x, y) REFERENCES p);"
    )
    assert platform.column_facts(model, "c", "y").foreign_key.column == "b"


def test_uniqueness_is_found_wherever_it_was_declared(model) -> None:
    unique = {
        c.name: platform.column_facts(model, "app.t", c.name).unique
        for c in model.tables[next(ref for ref in model.tables if ref.name == "t")].columns
    }
    assert {name for name, is_unique in unique.items() if is_unique} == {
        "pk_x",
        "id",
        "identifier",
        "created_at",
    }


def test_a_column_in_a_composite_unique_is_not_unique_on_its_own() -> None:
    model = platform.parse_schema("CREATE TABLE t (a INT, b INT, UNIQUE (a, b));")
    assert platform.column_facts(model, "t", "a").unique is False


def test_every_check_that_names_the_column_is_its(model) -> None:
    assert platform.column_facts(model, "app.t", "n").checks == (
        "n > 0",
        "n < 10 AND identifier <> ''",
    )
    assert platform.column_facts(model, "app.t", "identifier").checks == (
        "n < 10 AND identifier <> ''",
    )
    assert platform.column_facts(model, "app.t", "id").checks == ()


def test_the_type_is_the_models(model) -> None:
    facts = platform.column_facts(model, "app.t", "identifier")
    assert (facts.type_key, facts.raw_sql_type) == ("varchar(20)", "VARCHAR(20)")


def test_naming_hints_are_the_introspectors(model) -> None:
    hints = platform.naming_hints(model, "app.t")
    assert (hints.surrogate_pk, hints.natural_id) == ("pk_x", "id")
    bare = platform.naming_hints(platform.parse_schema("CREATE TABLE b (v INT);"), "b")
    assert (bare.surrogate_pk, bare.natural_id) == (None, None)


def test_a_column_the_table_lacks_is_a_key_error(model) -> None:
    with pytest.raises(KeyError, match="nope"):
        platform.column_facts(model, "app.t", "nope")
