"""Unit tests for pgTAP model generation."""

from __future__ import annotations

from datetime import UTC

from confiture.models.function_info import FunctionInfo, Volatility
from confiture.models.pgtap_models import PgTAPFile, PgTAPTest


def _make_func(
    name: str = "add",
    params: list | None = None,
    return_type: str = "integer",
) -> FunctionInfo:
    return FunctionInfo(
        schema="public",
        name=name,
        oid=1,
        params=params or [],
        return_type=return_type,
        returns_set=False,
        volatility=Volatility.IMMUTABLE,
        is_procedure=False,
        language="sql",
        source=None,
        estimated_cost=1.0,
    )


def test_pgtap_test_function_exists():
    func = _make_func(name="add")
    test = PgTAPTest.function_exists(func)
    assert "has_function" in test.sql
    assert "public" in test.sql
    assert "add" in test.sql
    assert test.test_name == "function public.add exists"


def test_pgtap_test_function_returns():
    func = _make_func(name="get_count", return_type="bigint")
    test = PgTAPTest.function_returns(func)
    assert "function_returns" in test.sql
    assert "bigint" in test.sql


def test_pgtap_test_function_volatility():
    func = _make_func(name="now_func")
    test = PgTAPTest.function_volatility(func)
    assert "immutable" in test.sql.lower() or "volatile" in test.sql.lower()
    assert "IMMUTABLE" in test.test_name or "immutable" in test.test_name


def test_pgtap_file_render_produces_valid_sql():
    from datetime import datetime

    func = _make_func()
    tests = [PgTAPTest.function_exists(func), PgTAPTest.function_returns(func)]
    pgtap_file = PgTAPFile(
        schema="public",
        database="mydb",
        generated_at=datetime.now(UTC).isoformat(),
        tests=tests,
        function_count=1,
    )
    sql = pgtap_file.render()
    assert "BEGIN;" in sql
    assert "ROLLBACK;" in sql
    assert f"SELECT plan({len(tests)});" in sql
    assert "has_function" in sql
    assert "Generated by confiture generate pgtap" in sql


def test_pgtap_file_render_includes_all_tests():
    from datetime import datetime

    func1 = _make_func(name="fn1")
    func2 = _make_func(name="fn2", return_type="text")
    tests = [
        PgTAPTest.function_exists(func1),
        PgTAPTest.function_exists(func2),
        PgTAPTest.function_returns(func2),
    ]
    pgtap_file = PgTAPFile(
        schema="public",
        database="mydb",
        generated_at=datetime.now(UTC).isoformat(),
        tests=tests,
        function_count=2,
    )
    sql = pgtap_file.render()
    assert "fn1" in sql
    assert "fn2" in sql
    assert "SELECT plan(3);" in sql
