"""Unit tests for stub model generation."""

from __future__ import annotations

from datetime import UTC

from confiture.core.introspection.type_mapping import TypeMapper
from confiture.models.function_info import FunctionInfo, FunctionParam, Volatility
from confiture.models.stub_models import StubFile, StubFunction, _to_pascal_case


def _make_info(
    name: str = "add",
    params: list | None = None,
    return_type: str = "integer",
    source: str | None = None,
    is_procedure: bool = False,
) -> FunctionInfo:
    return FunctionInfo(
        schema="public",
        name=name,
        oid=1,
        params=params or [],
        return_type=return_type,
        returns_set=False,
        volatility=Volatility.IMMUTABLE,
        is_procedure=is_procedure,
        language="sql",
        source=source,
        estimated_cost=1.0,
    )


def test_to_pascal_case():
    assert _to_pascal_case("create_booking") == "CreateBooking"
    assert _to_pascal_case("get_user") == "GetUser"
    assert _to_pascal_case("simple") == "Simple"


def test_stub_function_from_function_info_scalar():
    mapper = TypeMapper()
    info = _make_info(
        params=[
            FunctionParam(name="x", pg_type="integer"),
            FunctionParam(name="y", pg_type="integer"),
        ],
        return_type="integer",
    )
    stub = StubFunction.from_function_info(info, mapper)
    assert stub.name == "add"
    assert stub.python_params == [("x", "int"), ("y", "int")]
    assert stub.python_return == "int"
    assert stub.pydantic_model is None


def test_stub_function_from_procedure():
    mapper = TypeMapper()
    info = _make_info(name="do_work", return_type=None, is_procedure=True)
    stub = StubFunction.from_function_info(info, mapper)
    assert stub.is_procedure is True
    assert stub.python_return == "None"


def test_stub_function_jsonb_with_inference():
    mapper = TypeMapper()
    source = "RETURN jsonb_build_object('booking_id', v_id, 'state', v_state)"
    info = _make_info(name="create_booking", return_type="jsonb", source=source)
    stub = StubFunction.from_function_info(info, mapper)
    assert stub.pydantic_model_name == "CreateBookingResult"
    assert stub.python_return == "CreateBookingResult"
    assert stub.pydantic_model is not None
    assert "class CreateBookingResult" in stub.pydantic_model


def test_stub_function_jsonb_without_inference():
    mapper = TypeMapper()
    info = _make_info(name="get_data", return_type="jsonb", source="RETURN result;")
    stub = StubFunction.from_function_info(info, mapper)
    assert stub.python_return == "dict[str, Any]"
    assert stub.pydantic_model is None


def test_stub_function_render_function():
    mapper = TypeMapper()
    info = _make_info(
        params=[FunctionParam(name="x", pg_type="integer")],
        return_type="integer",
    )
    stub = StubFunction.from_function_info(info, mapper)
    code = stub.render_function()
    assert "def add(" in code
    assert "conn: psycopg.Connection" in code
    assert "x: int" in code
    assert "-> int:" in code
    assert "cur.execute" in code


def test_stub_file_render_produces_valid_python():
    from datetime import datetime

    mapper = TypeMapper()
    info = _make_info(
        params=[FunctionParam(name="x", pg_type="integer")],
        return_type="integer",
    )
    stub = StubFunction.from_function_info(info, mapper)
    stub_file = StubFile(
        schema="public",
        database="mydb",
        generated_at=datetime.now(UTC).isoformat(),
        functions=[stub],
        imports=stub.required_imports,
    )
    code = stub_file.render()
    assert "Generated by confiture generate stubs" in code
    compile(code, "<stub>", "exec")  # must be valid Python


def test_stub_file_render_includes_pydantic_model():
    from datetime import datetime

    mapper = TypeMapper()
    source = "RETURN jsonb_build_object('user_id', v_id, 'name', v_name)"
    info = _make_info(name="get_user", return_type="jsonb", source=source)
    stub = StubFunction.from_function_info(info, mapper)
    stub_file = StubFile(
        schema="public",
        database="mydb",
        generated_at=datetime.now(UTC).isoformat(),
        functions=[stub],
        imports=stub.required_imports,
    )
    code = stub_file.render()
    assert "class GetUserResult" in code
