"""Unit tests for ScaffoldOrchestrator — Phase 3 of issue #111.

All tests use pytest's ``tmp_path`` fixture.  No database required.
"""

from __future__ import annotations

from pathlib import Path

from confiture.core.scaffold.emitter import EmittedFunction
from confiture.core.scaffold.orchestrator import ScaffoldOrchestrator, ScaffoldResult

# ---------------------------------------------------------------------------
# ScaffoldResult
# ---------------------------------------------------------------------------


class TestScaffoldResult:
    """Tests for the ScaffoldResult dataclass."""

    def test_fields_accessible(self, tmp_path: Path) -> None:
        r = ScaffoldResult(path=tmp_path / "foo.sql", action="write")
        assert r.path == tmp_path / "foo.sql"
        assert r.action == "write"

    def test_skip_action(self, tmp_path: Path) -> None:
        r = ScaffoldResult(path=tmp_path / "foo.sql", action="skip")
        assert r.action == "skip"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_env(tmp_path: Path) -> tuple[Path, Path]:
    """Return (schema_dir, functions_dir) with functions_dir ready to use."""
    schema = tmp_path / "schema"
    funcs = schema / "functions"
    funcs.mkdir(parents=True)
    return schema, funcs


def _single_fn(subtree: Path, verb: str = "create", content: str = "SELECT 1;") -> EmittedFunction:
    return EmittedFunction(
        verb=verb,
        subtree=subtree,
        content=content,
        generated_marker="-- GENERATED by test-emitter v0.1",
    )


# ---------------------------------------------------------------------------
# Cycle 1: write path
# ---------------------------------------------------------------------------


class TestScaffoldWrite:
    """Tests for the basic write path of ScaffoldOrchestrator."""

    def test_writes_file_to_disk(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs)])

        assert len(results) == 1
        assert results[0].path.exists()

    def test_result_action_is_write(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs)])

        assert results[0].action == "write"

    def test_generated_header_in_file(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs)])

        text = results[0].path.read_text()
        assert "-- GENERATED by test-emitter v0.1" in text

    def test_generated_on_date_in_file(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs)])

        assert "Generated on:" in results[0].path.read_text()

    def test_take_ownership_note_in_file(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs)])

        assert "overrides/" in results[0].path.read_text()

    def test_sql_content_in_file(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs, content="SELECT 42;")])

        assert "SELECT 42;" in results[0].path.read_text()

    def test_header_precedes_content(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs, content="SELECT 42;")])

        text = results[0].path.read_text()
        header_pos = text.index("-- GENERATED")
        content_pos = text.index("SELECT 42;")
        assert header_pos < content_pos

    def test_filename_uses_verb(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs, verb="delete")])

        assert "_delete.sql" in results[0].path.name

    def test_path_inside_subtree(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs)])

        assert results[0].path.parent == funcs

    def test_multiple_functions_get_sequential_prefixes(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        fn1 = _single_fn(funcs, verb="create")
        fn2 = _single_fn(funcs, verb="update")
        results = orch.run([fn1, fn2])

        names = sorted(r.path.name for r in results)
        assert names[0].startswith("00001_")
        assert names[1].startswith("00002_")

    def test_multiple_functions_all_written(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs, "create"), _single_fn(funcs, "update")])

        assert all(r.action == "write" for r in results)
        assert all(r.path.exists() for r in results)

    def test_existing_files_not_overwritten(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        (funcs / "00001_existing.sql").write_text("-- existing")
        orch = ScaffoldOrchestrator(schema)

        results = orch.run([_single_fn(funcs, "create")])

        # New file gets prefix 2 — original is untouched
        assert results[0].path.name.startswith("00002_")
        assert (funcs / "00001_existing.sql").read_text() == "-- existing"


# ---------------------------------------------------------------------------
# Cycle 2: override skip
# ---------------------------------------------------------------------------


class TestScaffoldOverride:
    """Tests for the override-skip mechanism."""

    def test_skips_when_override_exists(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        overrides = tmp_path / "overrides"
        overrides_funcs = overrides / "functions"
        overrides_funcs.mkdir(parents=True)
        # Pre-create the override for the would-be first allocation
        (overrides_funcs / "00001_create.sql").write_text("-- my override")

        orch = ScaffoldOrchestrator(schema, overrides_dir=overrides)
        results = orch.run([_single_fn(funcs, "create")])

        assert results[0].action == "skip"

    def test_override_does_not_write_to_schema(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        overrides = tmp_path / "overrides"
        overrides_funcs = overrides / "functions"
        overrides_funcs.mkdir(parents=True)
        (overrides_funcs / "00001_create.sql").write_text("-- my override")

        orch = ScaffoldOrchestrator(schema, overrides_dir=overrides)
        results = orch.run([_single_fn(funcs, "create")])

        assert not results[0].path.exists()

    def test_no_overrides_dir_never_skips(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema, overrides_dir=None)

        results = orch.run([_single_fn(funcs, "create")])

        assert results[0].action == "write"

    def test_missing_overrides_dir_never_skips(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        overrides = tmp_path / "overrides_does_not_exist"
        orch = ScaffoldOrchestrator(schema, overrides_dir=overrides)

        results = orch.run([_single_fn(funcs, "create")])

        assert results[0].action == "write"

    def test_partial_override_only_skips_matching(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        overrides = tmp_path / "overrides"
        (overrides / "functions").mkdir(parents=True)
        # Only first function has an override
        (overrides / "functions" / "00001_create.sql").write_text("-- mine")

        orch = ScaffoldOrchestrator(schema, overrides_dir=overrides)
        results = orch.run([_single_fn(funcs, "create"), _single_fn(funcs, "update")])

        actions = {r.path.name.split("_", 1)[1]: r.action for r in results}
        assert actions["create.sql"] == "skip"
        assert actions["update.sql"] == "write"


# ---------------------------------------------------------------------------
# Cycle 3: dry run
# ---------------------------------------------------------------------------


class TestScaffoldDryRun:
    """Tests for dry_run=True — no disk writes."""

    def test_dry_run_does_not_create_files(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema, dry_run=True)

        results = orch.run([_single_fn(funcs)])

        assert not results[0].path.exists()

    def test_dry_run_result_action_is_write(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema, dry_run=True)

        results = orch.run([_single_fn(funcs)])

        assert results[0].action == "write"

    def test_dry_run_still_returns_allocated_path(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        orch = ScaffoldOrchestrator(schema, dry_run=True)

        results = orch.run([_single_fn(funcs, verb="create")])

        assert results[0].path.name.endswith("_create.sql")

    def test_dry_run_with_override_still_skips(self, tmp_path: Path) -> None:
        schema, funcs = _make_env(tmp_path)
        overrides = tmp_path / "overrides"
        (overrides / "functions").mkdir(parents=True)
        (overrides / "functions" / "00001_create.sql").write_text("-- mine")

        orch = ScaffoldOrchestrator(schema, overrides_dir=overrides, dry_run=True)
        results = orch.run([_single_fn(funcs, "create")])

        assert results[0].action == "skip"
